<?php

return [
    'site_title_separator' => ' - ',
    'text_edit' => 'Bearbeiten',
    'text_filter' => 'Filter',
    'text_clear' => 'Bereinigen',
    'text_search' => 'Suchen',
    'text_enabled' => 'Aktiviert',
    'text_disabled' => 'Deaktiviert',
    'text_active' => 'Aktiv',
    'text_inactive' => 'Inaktiv',
    'text_incomplete' => 'Unvollständig',
    'text_new' => 'Neu',
    'text_no' => 'Nein',
    'text_yes' => 'Ja',
    'text_none' => 'Kein',
    'text_hide' => 'Ausblenden',
    'text_show' => 'Zeigen',
    'text_action' => 'Aktion',
    'text_dashes' => ' -- ',
    'text_equals' => ' = ',
    'text_times' => 'x ',
    'text_plus' => '+ ',
    'text_please_select' => ' -Bitte auswählen- ',
    'text_use_default' => 'Standard verwenden',
    'text_updated' => 'aktualisiert',
    'text_added' => 'hinzugefügt',
    'text_deleted' => 'gelöscht',
    'text_default' => 'Standard',
    'text_select_all' => 'Alles auswählen',
    'text_select_none' => 'Nichts auswählen',
    'text_select' => 'Auswählen',
    'text_all_locations' => 'Alle Standorte',
    'text_selected' => 'Ausgewählt',
    'text_now' => 'Jetzt',
    'text_never' => 'Niemals',
    'text_remove' => 'Entfernen',
    'text_reload' => 'Aktualisieren',
    'text_save' => 'Speichern',
    'text_saving' => 'Speichern...',
    'text_resetting' => 'Zurücksetzen...',
    'text_loading' => 'wird geladen...',
    'text_deleting' => 'Wird gelöscht...',
    'text_about_tastyigniter' => 'Über TastyIgniter',
    'text_documentation' => 'Dokumentation',
    'text_community_support' => 'Community-Support',
    'text_empty' => 'Leer',
    'text_help' => 'Klicken Sie hier für Hilfe',
    'text_no_title' => 'Kein Titel',
    'text_allow' => 'Erlauben',
    'text_opening' => 'Eröffnung',
    'text_delivery' => 'Lieferung',
    'text_collection' => 'Abholung',

    'label_code' => 'Code',
    'label_name' => 'Name',
    'label_type' => 'Typ',
    'label_email' => 'E-Mail-Adresse',
    'label_status' => 'Status',
    'label_location' => 'Ort(e)',
    'label_description' => 'Beschreibung',

    'column_id' => 'ID',
    'column_location' => 'Ort(e)',
    'column_date_added' => 'Hinzugefügt am',
    'column_date_updated' => 'Aktualisierungsdatum',

    'text_filter_location' => 'Alle Standorte anzeigen',
    'text_filter_status' => 'Statusübersicht',
    'text_filter_date' => 'Alle Termine anzeigen',
    'text_back_link' => 'Zurück zur vorherigen Seite',
    'text_admin_link' => 'Zurück zum Admin Panel',

    'button_new' => '<i class="fa fa-plus"></i>&nbsp;&nbsp;Neu',
    'button_delete' => '<i class="fa fa-trash-o"></i>&nbsp;&nbsp;löschen',
    'button_add' => 'Hinzufügen',
    'button_edit' => 'Bearbeiten',
    'button_continue' => 'Weiter',
    'button_filter' => 'Filter',
    'button_save' => '<i class="fa fa-save"></i>&nbsp;&nbsp;Speichern',
    'button_save_close' => '<i class="fa fa-save"></i>&nbsp;&nbsp;Speichern & Schließen',
    'button_icon_back' => '<i class="fa fa-arrow-left px-0"></i>',
    'button_icon_filter' => '<i class="fa fa-times"></i>',
    'button_icon_delete' => '<i class="fa fa-trash-o"></i>',
    'button_close' => 'Schließen',
    'button_refresh' => '<i class="fa fa-refresh"></i>&nbsp;&nbsp;aktualisieren',

    'alert_success' => '%s erfolgreich.',
    'alert_error' => 'Ist ein Fehler aufgetreten, %s.',
    'alert_error_nothing' => 'Ein Fehler ist aufgetreten, nichts %s.',
    'alert_error_try_again' => 'Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut.',
    'alert_warning_confirm' => 'Dies kann nicht rückgängig gemacht werden! Sind Sie sicher, dass Sie dies tun wollen?',
    'alert_confirm' => 'Sind Sie sicher, dass Sie dies tun wollen?',
    'alert_user_not_logged_in' => 'Sie müssen angemeldet sein, auf diese Seite zugreifen zu können.',
    'alert_user_restricted' => 'Warnung: Sie haben nicht die richtige Berechtigung, bitte kontaktieren Sie den Systemadministrator.',
    'alert_location_restricted' => 'Warnung: Sie haben nicht die richtige Berechtigung, um auf den Kontext außerhalb Ihres Standortes zuzugreifen, kontaktieren Sie bitte den Systemadministrator.',
    'alert_warning_locationable_delete' => 'Warnung: Sie haben nicht die notwendige Berechtigung zum Löschen von Datensätzen, die an mehreren Stellen angehängt sind, wenden Sie sich bitte an den Systemadministrator.',
    'alert_form_error_message' => 'Entschuldigung, aber die Validierung des Formulars ist fehlgeschlagen, bitte überprüfen Sie nach Fehlern.',
    'alert_error_set_default' => '"%s" ist deaktiviert und kann nicht als Standard gesetzt werden.',
    'alert_missing_method' => 'Fehlende Methode [%s] in %s.',
    'alert_missing_model_definition' => "Das Modell '%s' enthält keine Definition für '%s'.",
    'alert_valid_values' => 'Gültige Werte für die Eigenschaft [locationAware] sind (none,show,hide).',
    'alert_widget_class_name' => "Der Widget-Klassenname '%s' wurde nicht registriert",
    'alert_missing_field_property' => "Fehlende Formularfeldeigenschaft 'modelClass' in '%s'",
    'alert_invalid_ajax_handler_name' => 'Ungültiger Ajax-Handler-Name: %s',
    'alert_invalid_ajax_partial_name' => 'Ungültiger partieller Name: %s',
    'alert_widget_not_bound_to_controller' => "Ein Widget mit dem Klassennamen '%s' wurde nicht an den Controller gebunden",
    'alert_user_not_logged' => 'Benutzer ist nicht eingeloggt',
    'alert_access_denied' => 'Zugang verweigert.',
    'alert_invalid_csrf_token' => 'Ungültiges Sicherheitstoken, bitte laden Sie die Seite neu und versuchen Sie es erneut.',
    
    'title_access_denied' => 'Zugang verweigert',
    'title_page_not_found' => 'No page found',
    'alert_page_not_found' => 'There\'s no page at this address, check the URL and try again.',

    'text_settings_title' => 'Einstellungen',
    'text_message_title' => 'Ihre Nachrichten',
    'text_activity_title' => 'Aktuelle Aktivitäten',
    'text_empty_activity' => 'Keine neuen Aktivitäten',
    'text_empty_message' => 'Keine Nachricht gefunden',
    'text_see_all_message' => 'Alle Nachrichten sehen',
    'text_see_all_activity' => 'Alle Aktivitäten anzeigen',
    'text_see_all_customers' => 'Alle Kunden ansehen',
    'text_see_all_orders' => 'Alle Bestellungen anzeigen',
    'text_user' => 'Benutzer',
    'text_staff_group' => 'Mitarbeitergruppen',
    'text_location' => 'Standort',
    'text_set_status' => 'Status setzen',
    'text_edit_details' => 'Details bearbeiten',
    'text_network_admin' => 'Netzwerk-Admin',
    'text_administration' => 'Administration',
    'text_logout' => 'Abmelden',
    'text_switch_to_assigned' => 'Zur Detailansicht wechseln',
    'text_switch_to_list' => 'Zur Listenansicht wechseln',

    'help_permalink' => 'Verwenden Sie NUR alphanumerische Kleinbuchstaben, Unterstriche oder Bindestriche und stellen Sie sicher, dass es EINZIGARTIG ist.',

    'staff_status' => [
        'text_set_status' => 'Status setzen',
        'text_online' => 'Online',
        'text_back_soon' => 'Bald zurück',
        'text_away' => 'Abwesend',
        'text_lunch_break' => 'Zu meiner Mittagspause...',
        'text_custom_status' => 'Wähle einen benutzerdefinierten Abwesenheitsstatus',
        'text_clear_tomorrow' => 'Morgen leeren',
        'text_clear_hours' => 'In 4 Stunden leeren',
        'text_clear_minutes' => 'In 30 Minuten leeren',
        'text_dont_clear' => 'Nicht leeren',
    ],

    'side_menu' => [
        'updates' => 'Updates',
        'storefront' => 'Startseite-Home',
        'page' => 'Statische Seiten',
        'system_logs' => 'Systemprotokolle',
        'setting' => 'Einstellungen',
        'dashboard' => 'Kontrollzentrum',
        'menu' => 'Menüelemente',
        'category' => 'Kategorien',
        'table' => 'Tische',
        'sale' => 'Verkäufe',
        'order' => 'Bestellungen',
        'reservation' => 'Reservierungen',
        'user' => 'Benutzer',
        'customer' => 'Kunden',
        'customer_group' => 'Gruppen',
        'staff_group' => 'Gruppen',
        'staff_role' => 'Rollen',
        'activities' => 'Aktivitäten',
        'restaurant' => 'Restaurant',
        'location' => 'Standorte',
        'marketing' => 'Marketing',
        'localisation' => 'Lokalisierung',
        'language' => 'Sprachen',
        'currency' => 'Währungen',
        'country' => 'Länder',
        'rating' => 'Bewertungen',
        'status' => 'Status',
        'mealtimes' => 'Essenszeiten',
        'extension' => 'Erweiterungen',
        'payment' => 'Zahlungen',
        'design' => 'Design',
        'theme' => 'Themes',
        'mail_template' => 'E-Mail-Vorlagen',
        'tool' => 'Werkzeuge',
        'media_manager' => 'Medienverwaltung',
        'system' => 'System',

        'alert_no_definition' => 'Keine Definition für Element %s.',
        'alert_invalid_menu' => 'Ungültiges Element angegeben.',
        'alert_menu_not_found' => 'Kein Hauptmenüpunkt für {%s} gefunden.',
        'alert_invalid_status' => 'Eine Statusmeldung ist erforderlich.',
    ],

    'list' => [
        'missing_model' => 'Listenaktion, die in %s verwendet wird, hat kein Modell definiert.',
        'missing_definitions' => 'Listenaktion, die in %s verwendet wird, hat keine Definitionen.',
        'invalid_column_datetime' => 'Spaltenwert \'%s\' ist kein DateTime Objekt, fehlt Ihnen eine $dates Referenz im Modell?',
        'delete_empty' => 'Nichts zum Löschen ausgewählt.',
        'missing_column' => 'Fehlende Spalten in Listdefinitionen %s',
        'text_empty' => 'Nichts gefunden.',
        'text_setup' => 'Konfiguration',
        'text_showing' => 'Zeige %s-%s von %s Datensätzen',
        'setup_title' => 'Listeneinstellung - %s',
        'label_visible_columns' => 'Sichtbare Spalten',
        'label_page_limit' => 'Einträge pro Seite',
        'button_reset_setup' => 'Reset',
        'button_cancel_setup' => 'Abbrechen',
        'button_apply_setup' => 'Änderungen übernehmen',
        'filter_missing_definitions' => "Die Modellklasse %s muss eine Methode %s definieren, die Optionen für den Filter '%s' zurückgibt.",
        'filter_missing_scope_definitions' => 'Keine Definition für Bereich %s',
        'help_visible_columns' => 'Legen Sie fest, welche Spalten sichtbar sind und in welcher Reihenfolge sie angezeigt werden sollen',
        'help_page_limit' => 'Beschränken, wie viele Datensätze pro Seite angezeigt werden',
        'alert_relationship_not_supported' => 'Die Beziehung %s wird für Listenspalten nicht unterstützt.',
        'missing_action_code' => 'Ungültiger Massenaktionscode angegeben.',
        'action_not_found' => 'Bulk Action-Klasse (%s) nicht gefunden',

        'actions' => [
            'text_select' => 'Wählen Sie eine anzuwendende Aktion',
            'label_edit' => 'Bearbeiten',
            'label_status' => 'Aktivieren/Deaktivieren',
            'label_enable' => 'Aktivieren',
            'label_disable' => 'Deaktivieren',
            'text_select_all' => 'Alle %s-Datensätze auswählen',
        ],
    ],

    'calendar' => [
        'missing_model' => 'Kalenderaktion, die in %s verwendet wird, hat kein Modell definiert.',
        'missing_definitions' => 'Kalenderaktion, die in %s verwendet wird, hat kein Modell definiert.',
        'missing_method' => "Kalender-Aktion '%s' enthält keine Methode '%s'.",
        'missing_partial' => "Kalender-Aktion, die in '%s' definiert ist, fehlt ein Popup-Teilchen.",
    ],

    'form' => [
        'create_title' => ':name: erstellen',
        'edit_title' => ':name: bearbeiten',
        'preview_title' => ':name: Vorschau',
        'missing_model' => 'Formularaktion, die in %s verwendet wird, hat kein Modell definiert.',
        'missing_definitions' => 'Formularfeld [%s] hat keine Definitionen.',
        'missing_definition' => 'Formularaktion enthält keine Felddefinition für: %s.',
        'missing_method' => "Formularaktion '%s' enthält keine Methode '%s'.",
        'undefined_tab' => 'Verschiedenes',
        'create_success' => '%s erfolgreich erstellt',
        'edit_success' => '%s erfolgreich aktualisiert',
        'delete_success' => '%s erfolgreich gelöscht',
        'create_failed' => '%s erstellen fehlgeschlagen',
        'edit_failed' => '%s -Update fehlgeschlagen',
        'delete_failed' => '%s Löschen fehlgeschlagen',
        'insert_row' => 'Zeile einfügen',
        'insert_row_below' => 'Zeile unten einfügen',
        'delete_row' => 'Zeile löschen',
        'not_ready' => 'Die Formularaktion wurde nicht initialisiert, überprüfen Sie, ob Sie initForm() in Ihrem Controller genannt haben.',
        'options_method_not_exists' => 'Die Modellklasse %s muss eine Methode %s für das Formularfeld [%s] festlegen.',
        'field_invalid_type' => 'Ungültiger Feldtyp verwendet %s.',
        'missing_id' => 'Formulardatennummer wurde nicht angegeben.',
        'not_found' => 'Formulardatensatz mit ID [%s] konnte nicht gefunden werden.',
        'mass_assignment_failed' => "Massenzuordnung fehlgeschlagen für Model Attribut ':attribute'.",
        'record_not_found' => 'Datensatz nicht gefunden.',
        'request_class_not_found' => 'Form Request Klasse (%s) nicht gefunden',
        'record_not_found_in_model' => 'Datensatz-ID [%s] nicht in Modell %s gefunden.',

        'save_actions' => [
            'continue' => 'Bearbeitung fortsetzen',
            'close' => 'Zur Auflistung gehen',
            'new' => 'Neu erstellen',
        ],
    ],

    'allergens' => [
        'text_title' => 'Allergene',
        'text_allergens' => 'Allergene',
        'text_form_name' => 'Allergen',
        'text_filter_search' => 'Suche nach Namen.',
        'text_empty' => 'Es sind keine Allergene verfügbar.',

        'label_image' => 'Bild',
        'help_photo' => 'Wählen Sie eine Datei aus, um das Allergenbild zu aktualisieren, ansonsten leer lassen.',
    ],

    'categories' => [
        'text_title' => 'Kategorien',
        'text_form_name' => 'Kategorie',
        'text_filter_search' => 'Suche nach Namen.',
        'text_empty' => 'Es stehen keine Kategorien zur Verfügung.',

        'column_parent' => 'Übergeordnete',
        'column_priority' => 'Priorität',

        'label_permalink_slug' => 'Slug',
        'label_parent' => 'Übergeordnete',
        'label_image' => 'Bild',
        'label_priority' => 'Priorität',

        'help_photo' => 'Wählen Sie eine Datei um das Kategorie Bild zu aktualisieren, ansonsten leer lassen.',
    ],

    'customer_groups' => [
        'text_title' => 'Kundengruppe',
        'text_form_name' => 'Kundegruppe',
        'text_empty' => 'Keine Kundengruppen verfügbar.',

        'column_customers' => '# Kunden',

        'label_approval' => 'Genehmigung',

        'alert_set_default' => 'Standort als Standard festgelegt',

        'help_approval' => 'Neukunden müssen genehmigt werden, bevor sie sich einloggen können.',
    ],

    'customers' => [
        'text_title' => 'Kunden',
        'text_form_name' => 'Kunde',
        'text_tab_general' => 'Kunde',
        'text_tab_address' => 'Adressen',
        'text_tab_orders' => 'Bestellungen',
        'text_tab_reservations' => 'Reservierungen',
        'text_filter_search' => 'Nach Name oder E-Mail-Adresse suchen.',
        'text_empty' => 'Es gibt keine Kunden.',
        'text_subscribe' => 'Abonnieren',
        'text_un_subscribe' => 'Abmelden',
        'text_title_edit_address' => 'Adresse',
        'text_impersonate' => 'Aus Nutzersicht betrachten',

        'column_full_name' => 'Ganzer Name',
        'column_telephone' => 'Telefon',
        'column_date_added' => 'Registrierungsdatum',

        'button_activate' => 'Manuell aktivieren',

        'label_first_name' => 'Vorname',
        'label_last_name' => 'Nachname',
        'label_password' => 'Kennwort',
        'label_confirm_password' => 'Kennwort bestätigen',
        'label_telephone' => 'Telefon',
        'label_newsletter' => 'Newsletter',
        'label_send_invite' => 'Einladungs-E-Mail senden',
        'label_customer_group' => 'Kundegruppe',
        'label_address_1' => 'Adresse 1',
        'label_address_2' => 'Adresse 2',
        'label_city' => 'Stadt',
        'label_state' => 'Bundesland',
        'label_postcode' => 'Postleitzahl',
        'label_country' => 'Land',

        'help_send_invite' => 'Sendet eine Einladungsnachricht mit einem Link zum Festlegen eines Passworts für das Konto.',
        'help_password' => 'Leer lassen, um Passwort unverändert zu lassen',

        'alert_login_restricted' => 'Warnung: Sie haben nicht die Berechtigung <b>auf ein Kundenkonto zuzugreifen</b>, bitte kontaktieren Sie den Systemadministrator.',
        'alert_impersonate_confirm' => 'Sind Sie sicher, dass Sie diesen Kunden imitieren möchten? Sie können zu Ihrem ursprünglichen Status zurückkehren, indem Sie sich abmelden.',
        'alert_impersonate_success' => 'Sie imitieren jetzt Kunde: %s',
        'alert_activation_success' => 'Kunde erfolgreich aktiviert.',
        'alert_customer_not_active' => "Benutzer '%s' kann nicht angemeldet werden, solange er nicht aktiviert ist.",
        'alert_customer_payment_profile_not_found' => 'Zahlungsprofil des Kunden nicht gefunden!',
    ],

    'dashboard' => [
        'text_title' => 'Kontrollzentrum',
        'text_heading' => 'Kontrollzentrum',
        'text_add_widget' => 'Widget hinzufügen',
        'text_edit_widget' => 'Widget bearbeiten',
        'text_select_widget' => 'Wähle ein Widget',

        'text_zero' => '0',
        'text_dash_dash' => '--',
        'text_today' => 'Heute',
        'text_delivery' => 'Lieferung',
        'text_collection' => 'Abholung',
        'text_no_activity' => 'Es stehen keine neuen Aktivitäten zur Verfügung.',
        'text_total_sale' => 'Verkäufe Gesamt',
        'text_total_lost_sale' => 'Gesamt Umsatz verloren',
        'text_total_cash_payment' => 'Summe Barzahlungen',
        'text_total_customer' => 'Kunden gesamt',
        'text_total_order' => 'Gesamten Bestellungen',
        'text_total_delivery_order' => 'Gesamtlieferung-Bestellungen',
        'text_total_collection_order' => 'Gesamte Abholungsaufträge',
        'text_total_completed_order' => 'Alle Abgeschlossene Aufträge',
        'text_total_reservation' => 'Gesamte Reservierungen',
        'text_total_reserved_guest' => 'Gäste gesamt',
        'text_total_completed_reservation' => 'Gesamte Reservierungen abgeschlossen',
        'text_total_reserved_table' => 'Alle Reservierte Tische',
        'text_complete_setup' => 'Restaurant-Setup abschließen',
        'text_progress' => 'Fertig',
        'text_progress_initial' => 'Ersteinrichtung',
        'text_progress_setting' => 'Ihre Restaurant-Einstellungen',
        'text_progress_menus' => 'Menüs hinzufügen',
        'text_progress_design' => 'Gestalten Sie Ihre Website-Hintergrund',
        'text_progress_email' => 'Test-Email senden',
        'text_progress_count' => '60%',
        'text_progress_summary' => 'Folgen Sie diesen Schritten, um Ihr Restaurant auf &amp; Online zu bekommen. ',
        'text_initial_progress' => '<b>Initiales Setup</b> - Legen Sie Ihre bevorzugten allgemeinen Einstellungen wie Restaurantname und E-Mail fest.',
        'text_settings_progress' => '<b>Ihre Restauranteinstellungen</b> - Lassen Sie Ihre Kunden Ihre Öffnungszeiten, Lieferzeiten, Vorbereitungszeit und wo sie sich befinden, wissen.',
        'text_menus_progress' => '<b>Menus</b> hinzufügen - Fügen Sie Ihr Menü mit unserem einfachen Editor hinzu. Zeigen Sie mehrere Menüs wie Lieferung &amp;. Essen, beinhaltet Größen und Mahlzeiten',
        'text_design_progress' => '<b>Design Ihrer Website-Hintergrund</b> - laden Sie Ihre eigenen oder wählen Sie ein Hintergrundbild für Ihre Website aus unserer Galerie.',
        'text_email_progress' => '<b>Test-E-Mail senden</b> - Bitte stellen Sie sicher, dass Bestellbestätigungs-E-Mails erfolgreich an Kunden gesendet werden.',
        'text_statistic' => 'Statistiken',
        'text_range' => 'Entfernung',
        'text_week' => 'Letzte 7 Tage',
        'text_month' => 'Letzte 30 Tage',
        'text_year' => 'Dieses Jahr',
        'text_context' => 'Kontext',
        'text_stats_card' => 'Karte',
        'text_charts_dataset' => 'Datensätze',
        'text_cache_usage' => 'Cache-Nutzung',
        'text_total_cache' => 'Gesamte Cache-Größe:',
        'text_news' => 'TastyIgniter News',
        'text_news_count' => 'Nachrichtenanzahl',
        'text_recent_activity' => 'Aktuelle Aktivitäten',
        'text_activities_count' => 'Anzahl Aktivitäten',
        'text_top_customers' => 'Top-Kunden',
        'text_latest_order' => '10 letzte Bestellungen',
        'text_reports_chart' => 'Reports Übersicht',
        'text_select_range' => 'Datumsbereich auswählen',
        'text_last_version_check' => 'Den letzten <b>TastyIgniter-Core-Version zu überprüfen</b>, wurde vor mehr als einer Woche. <a href="%s"> <b>Suchen Sie nach Updates</b></a>',

        'alert_select_widget_to_update' => 'Please select a widget to update.',
        'alert_select_widget_to_add' => 'Please select a widget to add.',
        'alert_widget_class_not_found' => 'The selected class does not exist.',
        'alert_invalid_widget' => 'The selected class is not a dashboard widget.',
        'alert_invalid_aliases' => 'Invalid aliases string.',
        'alert_invalid_priorities' => "'Invalid priorities string.'",
        'alert_invalid_data_posted' => 'Invalid data posted.',
        'alert_widget_not_found' => 'The specified widget is not found.',

        'onboarding' => [
            'title' => 'Erste Schritte',
            'label_settings' => 'Erforderliche Systemeinstellungen abschließen',
            'label_locations' => 'Standardstandort konfigurieren',
            'label_themes' => 'Passen Sie Ihre Website an',
            'label_extensions' => 'Empfohlene Erweiterungen installieren',
            'label_payments' => 'Zahlungs-Gateways konfigurieren',
            'label_menus' => 'Menü Artikel hinzufügen',
            'label_mail' => 'Test-E-Mail senden',

            'help_settings' => 'Bestätigen Sie alle erforderlichen Systemeinstellungen.',
            'help_locations' => 'Legen Sie Ihren Standard-Lieferbereich fest und passen Sie Ihre Öffnungszeiten an.',
            'help_themes' => 'Aktivieren und Anpassen des Front-End-Themes',
            'help_extensions' => 'Einige Erweiterungen werden empfohlen, damit Ihre Seite richtig funktioniert.',
            'help_payments' => 'Enable and configure a default payment method for your customers.',
            'help_menus' => 'Machen Sie Ihre Menü Artikel für die Bestellung verfügbar.',
            'help_mail' => 'Stellen Sie sicher, dass Bestellbestätigungs-E-Mails erfolgreich an Kunden gesendet werden.',
        ],

        'charts' => [
            'text_orders' => 'Bestellungen',
            'text_reservations' => 'Reservierungen',
            'text_customers' => 'Kunden',
        ],

        'column_location' => 'Standort',
        'column_ready_type' => 'Vorbereitungszeit',
        'column_total_orders' => '# Bestellungen',
        'column_total_sale' => 'Verkäufe Gesamt',

        'label_widget' => 'Widget',
        'label_widget_title' => 'Widget Titel',
        'label_widget_columns' => 'Widget-Grid-Breite',
        'label_widget_css_class' => 'Widget-CSS-Klasse',

        'button_add_widget' => 'Widget hinzufügen',
        'button_reset_widgets' => 'Widgets zurücksetzen',
        'button_set_default' => 'Als Standard festlegen',

        'help_widget_columns' => 'Die Widget-Breite, eine Zahl zwischen 1 und 12.',

        'error_rss' => 'Die URL Adresse ist falsch oder',

        'alert_set_default_confirm' => 'Sind Sie sicher, dass Sie das aktuelle Layout als Standard festlegen möchten?',
        'alert_reset_layout_success' => 'Layout erfolgreich zurückgesetzt',
    ],

    'locations' => [
        'text_title' => 'Standorte',
        'text_form_name' => 'Standort',
        'text_tab_general' => 'Standort',
        'text_tab_schedules' => 'Schedules',
        'text_tab_options' => 'Optionen',
        'text_tab_general_options' => 'Allgemeine Optionen',
        'text_tab_delivery' => 'Lieferung',
        'text_tab_gallery' => 'Galerie',
        'text_tab_title_address' => 'Adresse',
        'text_filter_search' => 'Suche nach Name, Stadt oder Staat.',
        'text_empty' => 'Es stehen keine Standorte zur Verfügung.',
        'text_24_7' => '24/7',
        'text_daily' => 'Täglich',
        'text_flexible' => 'Flexibel',
        'text_timesheet' => 'Timesheet',
        'text_schedule' => 'Schedule',
        'text_title_schedule' => 'Edit %s schedule',
        'text_same_as' => 'Same as %s hours',
        'text_open' => 'Geöffnet',
        'text_closed' => 'Geschlossen',
        'text_circle' => 'Kreis',
        'text_shape' => 'Form (Polygon)',
        'text_custom' => 'Adresse',
        'text_address_component_street' => 'Mit Straßennamen abgleichen',
        'text_address_component_town' => 'Mit Stadt oder Sub-Ort abgleichen',
        'text_address_component_city' => 'Mit Stadt oder Ort abgleichen',
        'text_address_component_region' => 'Übereinstimmung nach Region oder Verwaltungsgebiet Level 2',
        'text_address_component_state' => 'Übereinstimmung nach Bundesland oder Verwaltungsgebiet Level 1',
        'text_address_component_postal_code' => 'Mit Postleitzahl abgleichen',
        'text_delivery_area' => 'Liefergebiete',
        'text_add_new_area' => 'Neuen Bereich hinzufügen',
        'text_edit_area' => 'Liefergebiet',
        'text_all_orders' => 'alle',
        'text_above_order_total' => 'über',
        'text_below_order_total' => 'unter',
        'text_asap_only' => 'Nur ASAP',
        'text_later_only' => 'Nur später',

        'column_city' => 'Stadt',
        'column_state' => 'Bundesland',
        'column_postcode' => 'Postleitzahl',
        'column_telephone' => 'Telefon',

        'label_address_1' => 'Adresse 1',
        'label_address_2' => 'Adresse 2',
        'label_city' => 'Stadt',
        'label_state' => 'Bundesland',
        'label_postcode' => 'Postleitzahl',
        'label_country' => 'Land',
        'label_auto_lat_lng' => 'Dreh/lng automatisch abrufen',
        'label_latitude' => 'Breitengrad',
        'label_longitude' => 'Längengrad',
        'label_radius' => 'Lieferradius',
        'label_telephone' => 'Telefon',
        'label_permalink_slug' => 'Slug',
        'label_image' => 'Bild',
        'label_schedule_name' => 'Name',
        'label_schedule_type' => 'Type',
        'label_schedule_days' => 'Days',
        'label_schedule_hours' => 'Hours',
        'label_schedule_open' => 'Start Time',
        'label_schedule_close' => 'End Time',
        'label_area_shape' => 'Bereichsform',
        'label_area_circle' => 'Bereich Kreis',
        'label_area_vertices' => 'Bereichskanten',
        'label_area_type' => 'Bereich typ',
        'label_area_default' => 'Als Standard festlegen',
        'label_area_id' => 'Bereich ID',
        'label_area_name' => 'Bereichsnamen',
        'label_area_charge' => 'Gesamtsumme',
        'label_area_distance' => 'Entfernung (Meile/Kilometer)',
        'label_address_component' => 'Adresskomponente',
        'label_address_component_type' => 'Adress-Komponententyp',
        'label_address_component_value' => 'Adresskomponentenwert',
        'label_charge_condition' => 'Regel',
        'label_area_min_amount' => 'Summe',
        'label_gallery_title' => 'Titel',
        'label_gallery_add_image' => 'Bild hinzufügen',
        'label_gallery_image_thumbnail' => 'Miniaturansicht',
        'label_gallery_image_name' => 'Dateiname',
        'label_gallery_image_alt' => 'Alternativer Text',
        'label_delivery_condition' => 'Lieferbedingungen',
        'label_delivery_distance' => 'Entfernungsabhängige Zustellgebühr Bedingung',

        'error_no_zero_total' => 'Die %s kann kein Wert Null für andere Bedingungen als \'bei allen Bestellungen\' sein.',
        'alert_delivery_area' => 'To allow your customers to find this location, please add delivery area(s) under the \'Delivery\' tab.',
        'alert_set_default' => 'Standort als Standard setzen',
        'alert_missing_map_center' => 'Map is missing center coordinates, please enter an address then click save.',
        'alert_missing_map_config' => 'Missing Google Maps Javascript Library, please provide your maps api key on the general system settings page.',
        'alert_invalid_area' => 'Ungültiger Bereich ausgewählt.',
        'alert_schedule_not_loaded' => 'Zeitplan nicht geladen.',
        'alert_invalid_schedule_type' => "Der definierte Parameter '%s' ist kein gültiger Arbeitstyp.",

        'help_permalink_disabled' => 'Permalink ist deaktiviert, wenn der einzelne Standortmodus aktiviert ist.',
        'help_image' => 'Wählen Sie ein Logo für diesen Standort.',
        'help_guest_order' => 'Erlauben Sie dem Kunden, eine Bestellung aufzugeben, ohne ein Konto einzurichten, oder verwenden Sie die Standardeinstellungen des Systems.',
        'help_flexible_hours' => 'Beginnen Sie mit dem Tippen, um die Öffnungszeiten festzulegen, z. B. 09:00-01:00 oder 09:00-10:00, 19:00-01:00',
        'help_delivery_areas' => 'Lieferbedingungen an bestimmte geographische Bereiche/Grenzen festlegen. Lieferbereiche werden in der Reihenfolge angewendet, in der sie angezeigt werden. Jeder Standort muss mindestens einen Lieferbereich haben, um Lieferaufträge anzunehmen.',
        'help_delivery_condition' => 'Verwenden Sie die Tabelle unten, um unterschiedliche Lieferungsbedingungen zu setzen. Bedingungen/Regeln werden in der Reihenfolge angewendet, in der sie erscheinen. Für kostenlose Lieferung auf 0 oder -1, um die Lieferung nicht verfügbar zu machen. Wenn eine "alle" Regel vorhanden ist, wird keine andere Bedingung angewendet.',
        'help_delivery_components' => 'Alle Regeln müssen Gültig sein, um diesen Lieferbereich anzuwenden. Jede Regel wird mit der Adresskomponente des Benutzers abgestimmt. Werte können reguläre Ausdrücke enthalten.',
        'help_delivery_distance' => 'Fügen Sie zusätzliche Gebühren auf der Grundlage der Lieferentfernung pro Einheit hinzu. Diese werden zusätzlich zu den Gebühren für die Lieferbedingungen erhoben. Die Regeln werden in der Reihenfolge angewendet, in der sie erscheinen.',
    ],

    'login' => [
        'text_title' => 'Anmelden',
        'text_password_reset_title' => 'Kennwort zurücksetzen',
        'text_forgot_password' => 'Kennwort vergessen?',
        'text_reset_password_title' => 'Setzen Sie Ihr Passwort zurück',
        'text_back_to_login' => 'Zurück zur Anmeldeseite',

        'button_login' => 'Anmelden',
        'button_reset_password' => 'Kennwort zurücksetzen',

        'label_reset_code' => 'Zurücksetzungscode',
        'label_username' => 'Benutzername',
        'label_password' => 'Kennwort',
        'label_password_confirm' => 'Kennwort bestätigen',

        'alert_username_not_found' => 'Login fehlgeschlagen, bitte versuchen Sie es erneut oder kontaktieren Sie den Systemadministrator!',
        'alert_success_reset' => 'Dein Passwort wurde erfolgreich verändert.',
        'alert_failed_reset' => 'Der Reset-Code ist entweder ungültig oder abgelaufen.',
        'alert_success_logout' => 'Sie sind jetzt abgemeldet.',
        'alert_email_sent' => 'Wir haben einen Link zum Zurücksetzen des Passworts an Ihre E-Mail gesendet.',
        'alert_email_not_sent' => 'Die E-Mail konnte nicht gesendet werden. Möglicher Grund: Ihr Host hat die Mail()-Funktion möglicherweise deaktiviert.',
    ],

    'mealtimes' => [
        'text_title' => 'Essenszeiten',
        'text_form_name' => 'Mahlzeit',
        'text_empty' => 'Es gibt keine Mahlzeiten, Bitte einfügen.',

        'column_mealtime_id' => 'ID',
        'column_mealtime_name' => 'Name',
        'column_start_time' => 'Startzeit',
        'column_end_time' => 'Endzeit',

        'label_mealtime_name' => 'Mahlzeit Name',
        'label_start_time' => 'Startzeit',
        'label_end_time' => 'Endzeit',
    ],

    'menu_options' => [
        'text_title' => 'Menü-Optionen',
        'text_form_name' => 'Menüoption',
        'text_tab_general' => 'Allgemein',
        'text_tab_values' => 'Optionswerte',
        'text_empty' => 'Es gibt keine Menüoptionen.',
        'text_filter_search' => 'Nach Namen oder Preis suchen.',
        'text_filter_display_type' => 'Alle Anzeigetypen anzeigen',
        'text_select' => 'Wählen',
        'text_radio' => 'Radio',
        'text_checkbox' => 'Checkbox',
        'text_quantity' => 'Menge',
        'is_required' => 'ist erforderlich',
        'is_not_required' => 'ist nicht erforderlich',
        'text_option' => 'Option',
        'text_option_summary' => 'Als %s HTML-Element anzeigen',

        'column_display_type' => 'Anzeigeart',

        'label_option_name' => 'Optionsname',
        'label_priority' => 'Priorität',
        'label_display_type' => 'Anzeigeart',
        'label_option_values' => 'Optionswerte',
        'label_option_value' => 'Optionswert',
        'label_option_price' => 'Optionspreis',
        'label_option_id' => 'Option-ID',
        'label_update_related_menu_item' => 'Optionswerte der zugehörigen Menüpunkte aktualisieren',
    ],

    'menus' => [
        'text_title' => 'Menüs',
        'text_form_name' => 'Menü',
        'text_tab_general' => 'Menü',
        'text_tab_menu_option' => 'Optionen',
        'text_tab_special' => 'Angebote',
        'text_empty' => 'Es stehen keine Menüs zur Verfügung.',
        'text_filter_search' => 'Suche nach Name, Preis oder Lagerqualität.',
        'text_filter_category' => 'Alle Kategorien anzeigen',
        'text_mealtime_all' => 'Ganztägig verfügbar',
        'text_delivery_only' => 'nur Lieferung',
        'text_collection_only' => 'Nur Abholung',
        'text_fixed_amount' => 'Festbetrag',
        'text_percentage' => 'Prozent',
        'text_forever' => 'Dauerhaft',
        'text_period' => 'Periode',
        'text_recurring' => 'Wiederkehrend',

        'column_category' => 'Kategorie',
        'column_price' => 'Preis',
        'column_stock_qty' => 'Lagermenge',

        'label_price' => 'Preis',
        'label_category' => 'Kategorie',
        'label_image' => 'Bild',
        'label_stock_qty' => 'Lagermenge',
        'label_minimum_qty' => 'Mindestbestellmenge',
        'label_mealtime' => 'Mahlzeit',
        'label_order_restriction' => 'Bestellungsbeschränkung',
        'label_menu_priority' => 'Priorität',
        'label_special_status' => 'Besonderen Status',
        'label_option' => 'Option',
        'label_menu_option' => 'Menüoption',
        'label_option_id' => 'Option-ID',
        'label_option_name' => 'Optionsname',
        'label_option_display_type' => 'Optionsanzeigetyp',
        'label_option_priority' => 'Options-Priorität',
        'label_option_required' => 'Option erforderlich',
        'label_option_value' => 'Optionswert',
        'label_option_price' => 'Optionspreis',
        'label_option_qty' => 'Lagermenge',
        'label_option_default_value' => 'Standard',
        'label_option_value_id' => 'ID',
        'label_min_selected' => 'Min. ausgewählt',
        'label_max_selected' => 'Max ausgewählt',
        'label_start_date' => 'Start Datum',
        'label_end_date' => 'End Datum',
        'label_special_price' => 'Sonderpreis',
        'label_special_type' => 'Spezieller Typ',
        'label_allergens' => 'Allergene',
        'label_validity' => 'Gültigkeit',
        'label_recurring_every' => 'Wiederkehrende jeden',
        'label_recurring_from_time' => 'Wiederkehrende von Zeit',
        'label_recurring_to_time' => 'Wiederkehrende, Zeit',

        'help_image' => 'Wählen Sie eine Datei, um das Menü Bild zu aktualisieren, ansonsten leer lassen.',
        'help_mealtime' => 'Legen Sie fest, welche Tageszeit Ihre Kunden dieses Menü bestellen können. Mahlzeiten können unter Küche > Mahlzeiten verwaltet werden',
        'help_stock_qty' => 'Geben Sie den verfügbaren Lagerbestand ein. Dieser Betrag kann auf Null gesetzt werden, um eine unbegrenzte Lagermenge zu erhalten. Oder eine negative Zahl um zu repräsentieren, das das Lager leer ist.',
        'help_minimum_qty' => 'Geben Sie die Mindestmenge ein, die von Kunden bestellt werden kann.',
        'help_subtract_stock' => 'Wählen Sie Ja für die bestellte Menü- und Optionenmenge, die von der ursprünglichen Lagermenge abgezogen werden soll.',
        'help_menu_option' => 'Wählen Sie aus der Dropdown-Liste, um diesem Menüeintrag eine Option hinzuzufügen.',
        'help_order_restriction' => 'Gibt an, ob das Menü auf einen bestimmten Bestellart beschränkt werden soll.',
        'help_min_selected' => 'Minimale Anzahl von Elementen, die aus diesen Optionen ausgewählt werden sollen, leer lassen um sie zu ignorieren.',
        'help_max_selected' => 'Maximale Anzahl von Elementen, die aus diesen Optionen ausgewählt werden sollen, leer lassen um sie zu ignorieren.',
        'help_option_required' => 'Wählen Sie Aktiviert, wenn ein Kunde diese Option auswählen muss. Wenn diese Option nicht erforderlich ist, wählen Sie Deaktiviert.',
        'help_specials' => 'Wählen Sie Deaktivieren um Specials zu deaktivieren. Wählen Sie Aktivieren, um Special zu aktivieren und das Startdatum, Enddatum und Preis Ihres Sonderartikels einzugeben.',
    ],

    'orders' => [
        'text_title' => 'Bestellungen',
        'text_form_name' => 'Bestellung',
        'text_invoice_heading' => 'Bestellrechnung: %s',
        'text_tab_general' => 'Bestellung',
        'text_status_history' => 'Status History',
        'text_payment_logs' => 'Zahlungsversuche',
        'text_tab_menu' => 'Menüelemente',
        'text_empty' => 'Es sind keine Bestellungen verfügbar.',
        'text_filter_search' => 'Suche nach Id, Standort, Status, Personal oder Kundennamen.',
        'text_filter_assignee' => 'Alle Zugeordneten anzeigen',
        'text_filter_order_type' => 'Alle Auftragsarten anzeigen',
        'text_filter_payment' => 'Alle Zahlungen anzeigen',
        'text_delivery' => 'Lieferung',
        'text_collection' => 'Abholen',
        'text_invoice' => 'Rechnung',
        'text_restaurant' => 'Standort',
        'text_customer' => 'Kunde',
        'text_payment' => 'Bezahlung',
        'text_invoice_no' => 'Rechnung #',
        'text_invoice_date' => 'Rechnungsdatum',
        'text_order_date' => 'Bestelldatum',
        'text_deliver_to' => 'Liefern an',
        'text_asap' => 'ASAP',
        'text_invoice_thank_you' => 'Der Rechnungsbetrag für Speisen und Liefergebühr enthält die Umsatzsteuer von 7%. Der Rechnungsbetrag für Getränke enthält die Umsatzsteuer von 19%.',
        'text_collection_order_type' => 'Dies ist eine Abholung-Bestellung',
        'text_no_payment' => 'Keine Zahlungsmethode ausgewählt',
        'text_unassigned' => 'Muss noch zugewiesen werden',
        'text_assigned_to_self' => 'Mir zugewiesen',
        'text_assigned_to_others' => 'Anderem Personal zugewiesen',

        'button_print_invoice' => '<i class="fa fa-receipt"></i>&nbsp;&nbsp;Rechnung ansehen',

        'column_location' => 'Standort',
        'column_customer_name' => 'Kundenname',
        'column_payment' => 'Bezahlung',
        'column_total' => 'Summe',
        'column_time' => 'Bestellzeit',
        'column_date' => 'Bestelldatum',
        'column_time_date' => 'Datum Zeit',
        'column_staff' => 'Mitarbeiter',
        'column_comment' => 'Kommentar',
        'column_assignee' => 'Zugewiesen an',
        'column_assignee_group' => 'Zugewiesen an Gruppe',
        'column_notify' => 'Kunde informiert',
        'column_name_option' => 'Name/Optionen',
        'column_price' => 'Preis',
        'column_quantity' => 'Menge',

        'label_order_id' => 'Bestell-Nr.',
        'label_customer_name' => 'Kundenname',
        'label_telephone' => 'Telefon',
        'label_delivery_address' => 'Lieferadresse',
        'label_order_type' => 'Auftragsart',
        'label_time_is_asap' => 'Bestellzeit sofort',
        'label_order_time' => 'Lieferung/Abholung-up Zeit',
        'label_order_date' => 'Lieferung/Abholung-up Zeit',
        'label_order_date_time' => 'Zustellung/Abholung Datum Uhrzeit',
        'label_date_added' => 'Datum hinzugefügt',
        'label_order_total' => 'Gesamtsumme',
        'label_comment' => 'Bestellungskommentar',
        'label_delivery_comment' => 'Hinweise zur Lieferung',
        'label_date_modified' => 'Datum geändert',
        'label_user_agent' => 'Benutzer-Agent',
        'label_ip_address' => 'IP Adresse',
        'label_invoice' => 'Rechnung',
        'label_assign_staff' => 'Beauftragter',
        'label_restaurant_name' => 'Name',
        'label_restaurant_address' => 'Anschrift',
        'label_payment_method' => 'Zahlungsmethode',
        'label_total_items' => 'Artikel insgesamt',

        'activity_event_log_title' => 'Bestellstatus aktualisiert',
        'activity_event_log_assigned_title' => 'Bestellung zugewiesen',
        'activity_event_log' => 'aktualisierte Bestellung (#:properties.order_id) Status auf <b>:properties.status_name</b>',
        'activity_event_log_assigned' => 'zugewiesene Bestellung (#:properties.order_id) an',
    
        'alert_invoice_not_generated' => 'Die Rechnung ist noch nicht erstellt worden.',
    ],

    'payments' => [
        'text_title' => 'Zahlungen',
        'text_form_name' => 'Bezahlung',
        'text_tab_config' => 'Konfiguration',
        'text_filter_search' => 'Suche nach Name oder Beschreibung.',
        'text_empty' => 'Es sind keine Zahlungen verfügbar.',

        'label_payments' => 'Zahlungs-Gateways',
        'label_code' => 'Eindeutiger Code',
        'label_default' => 'Ist Standard',
        'label_priority' => 'Priorität',

        'alert_setting_missing_id' => 'Der Erweiterungs-Einstellungscode wurde nicht angegeben.',
        'alert_invalid_code' => 'Ungültiger Code für das Zahlungsgateway ausgewählt.',
        'alert_code_not_found' => 'Zahlungsgateway mit Code %s kann nicht gefunden werden',
        'alert_update_payment_profile' => 'Die Methode updatePaymentProfile() wird vom Zahlungs-Gateway nicht unterstützt.',
        'alert_delete_payment_profile' => 'Die Methode deletePaymentProfile() wird von dem Zahlungs-Gateway nicht unterstützt.',
        'alert_pay_from_payment_profile' => 'Die Methode payFromPaymentProfile() wird vom Zahlungs-Gateway nicht unterstützt.',
    ],

    'permissions' => [
        'name' => 'Administration',
        'dashboard' => 'Dashboard-Widgets verwalten',
        'categories' => 'Menükategorien erstellen, bearbeiten und löschen',
        'customer_groups' => 'Kundengruppen verwalten',
        'customers' => 'Kunden erstellen, bearbeiten und löschen',
        'impersonate_staff' => 'Fähigkeit Mitarbeiter zu imitieren',
        'impersonate_customers' => 'Fähigkeit Kunden zu imitieren',
        'locations' => 'Orte erstellen, bearbeiten und löschen',
        'menus' => 'Menü Artikel erstellen, bearbeiten und löschen',
        'orders' => 'Bestellungen Bearbeiten',
        'delete_orders' => 'Bestellung löschen',
        'delete_reservations' => 'Reservierungen löschen',
        'assign_orders' => 'Bestellungen zuweisen',
        'assign_reservations' => 'Reservierungen zuweisen',
        'payments' => 'Zahlungsgateways verwalten',
        'reservations' => 'Reservierungen verwalten',
        'staff_groups' => 'Personalgruppen verwalten',
        'staffs' => 'Mitarbeiter erstellen, bearbeiten und löschen',
        'statuses' => 'Bestell- und Reservierungsstatus verwalten',
        'tables' => 'Reservierte Tische erstellen, bearbeiten und löschen',
        'mealtimes' => 'Mahlzeiten erstellen, bearbeiten und löschen',
        'allergens' => 'Allergene erstellen, bearbeiten und löschen',
    ],

    'reservations' => [
        'text_title' => 'Reservierungen',
        'text_form_name' => 'Reservierung',
        'text_tab_general' => 'Reservierung',
        'text_tab_restaurant' => 'Restaurant',
        'text_status_history' => 'Status History',
        'text_empty' => 'Es stehen keine Reservierungen zur Verfügung.',
        'text_filter_assignee' => 'Alle Zugeordneten anzeigen',
        'text_filter_search' => 'Suche nach Id, Standort, Gastnummer, Status, Kunde oder Tischnamen.',
        'text_switch_to_calendar' => 'Umstellung auf Ansicht Kalender',
        'text_no_booking' => 'Keine Buchungen',
        'text_restaurant' => 'Standort',
        'text_unassigned' => 'Muss noch zugewiesen werden',
        'text_assigned_to_self' => 'Mir zugewiesen',
        'text_assigned_to_others' => 'Anderem Personal zugewiesen',

        'column_location' => 'Standort',
        'column_customer_name' => 'Name',
        'column_guest' => 'Gast/Gäste',
        'column_table' => 'Tisch',
        'column_staff' => 'Mitarbeiter',
        'column_assignee' => 'Zugewiesen an',
        'column_assignee_group' => 'Zugewiesen an Gruppe',
        'column_notify' => 'Kunde informiert',
        'column_comment' => 'Kommentar',
        'column_date_time' => 'Datum - Zeit',
        'column_time' => 'Zeit',
        'column_date' => 'Datum',

        'label_reservation_id' => 'Reservierungs-ID',
        'label_customer_name' => 'Kundenname',
        'label_guest' => 'Gast Nummer',
        'label_reservation_date' => 'Reservierungsdatum',
        'label_reservation_time' => 'Reservierungszeit',
        'label_reservation_duration' => 'Reservierungsdauer',
        'label_occasion' => 'Gelegenheit',
        'label_date_added' => 'Datum hinzugefügt',
        'label_date_modified' => 'Datum geändert',
        'label_send_confirmation' => 'Reservierungsbestätigung senden',
        'label_user_agent' => 'Benutzer-Agent',
        'label_ip_address' => 'IP Adresse',
        'label_assign_staff' => 'Mitarbeiter zuweisen',
        'label_restaurant_name' => 'Name des Restaurants',
        'label_restaurant_address' => 'Adresse des Restaurants',
        'label_table_name' => 'Tischname',
        'label_table_capacity' => 'Maximale Kapazität der Tische',
        'label_table_min_capacity' => 'Maximale Kapazität der Tische',
        'label_first_name' => 'Vorname',
        'label_last_name' => 'Nachname',
        'label_customer_telephone' => 'Telefon',

        'help_reservation_duration' => 'Aufenthalt in Minuten. Leer lassen, um die Standardzeit zu verwenden',

        'activity_event_log_title' => 'Reservierungsstatus aktualisiert',
        'activity_event_log_assigned_title' => 'Reservierung zugewiesen',
        'activity_event_log' => 'aktualisierte Reservierung (#:properties.reservation_id) Status auf <b>:properties.status_name</b>',
        'activity_event_log_assigned' => 'zugewiesene Reservierung (#:properties.reservation_id) zu',
    
        'alert_no_reservation_found' => 'Keine passende Reservierung gefunden.',
    ],

    'settings' => [
        'text_tab_setup' => 'Setup',
        'text_tab_tax' => 'Steuer',
        'text_tab_user' => 'Benutzer',

        'text_tab_desc_user' => 'Konfigurieren von Registrierungs-E-Mail-Bestätigung, Standard-Kundengruppe, ...',
        'text_tab_desc_setup' => 'Bestell- und Reservierungseinstellungen konfigurieren',
        'text_tab_desc_tax' => 'Konfigurieren Sie die Steuereinstellungen',
    ],

    'staff_groups' => [
        'text_title' => 'Mitarbeitergruppen',
        'text_form_name' => 'Mitarbeitergruppen',
        'text_empty' => 'Es gibt keine Personalgruppen.',
        'text_round_robin' => 'Reihum',
        'text_load_balanced' => 'Lastverteilung',

        'label_auto_assign' => 'Automatische Auftragsvergabe',
        'label_assignment_mode' => 'Auftragsmodus',
        'label_assignment_availability' => 'Auftrags Verfügbarkeit',
        'label_load_balanced_limit' => 'Ladebalanciertes Limit',

        'column_users' => '# Benutzer',

        'alert_no_available_assignee' => 'Kein verfügbarer Empfänger.',

        'help_auto_assign' => 'Die Anzahl der Aufträge, die dem Personal dieser Gruppe zugewiesen wurden, verteilen und kontrollieren.',
        'help_round_robin' => 'Weisen Sie den Mitarbeitern Aufträge zu, die kreisförmig online sind.',
        'help_load_balanced' => 'Limitiert die Anzahl der Aufträge, die ein Mitarbeiter gleichzeitig erledigen kann.',
        'help_load_balanced_limit' => 'Maximale Anzahl von Bestellungen pro Mitarbeiter.',
        'help_assignment_availability' => 'Mitarbeitern erlauben, ihre Verfügbarkeit für automatische Auftragsabwicklung zu kontrollieren',
    ],

    'staff_roles' => [
        'text_title' => 'Personal Rollen',
        'text_form_name' => 'Mitarbeiter Rollen',
        'text_tab_permission' => 'Berechtigungen',
        'text_empty' => 'Es gibt keine Mitarbeiter Rollen.',

        'label_permissions' => 'Berechtigungen',
    ],

    'staff' => [
        'text_title' => 'Mitarbeiter',
        'text_form_name' => 'Mitarbeiter',
        'text_filter_search' => 'Suche nach Standort, Name oder E-Mail.',
        'text_filter_role' => 'Alle Rollen anzeigen',
        'text_filter_group' => 'Alle Gruppen anzeigen',
        'text_empty' => 'Es stehen keine Mitarbeiter zur Verfügung.',
        'text_roles_scope_groups' => 'Scope, Rollen und Gruppen',
        'text_sale_permission_global_access' => 'Weltweiter Zugriff',
        'text_sale_permission_groups' => 'Gruppen',
        'text_sale_permission_restricted' => 'Eingeschränkter Zugriff',
        'text_impersonate' => 'Als Mitarbeiter ausgeben',

        'column_group' => 'Mitarbeitergruppen',
        'column_role' => 'Mitarbeiter Rollen',
        'column_location' => 'Standorte',
        'column_last_login' => 'Letzte Anmeldung',

        'label_super_staff' => 'Seiten Administrator',
        'label_username' => 'Benutzername',
        'label_send_invite' => 'Einladungs-E-Mail senden',
        'label_password' => 'Kennwort',
        'label_confirm_password' => 'Kennwort bestätigen',
        'label_role' => 'Rolle',
        'label_group' => 'Gruppen',
        'label_language' => 'Sprache',
        'label_location' => 'Standorte',
        'label_sale_permission' => 'Bestell- und Reservierungsbereich',

        'help_send_invite' => 'Sendet eine Einladungsnachricht mit einem Link zum Festlegen eines Kennworts für ihr Konto.',
        'help_super_staff' => 'Gewährt diesem Personal unbegrenzten Zugriff auf alle Bereiche des Systems. Super-Mitarbeiter können andere Mitarbeiter hinzufügen und verwalten.',
        'help_role' => 'Rollen definieren Personalberechtigungen, die auf der Benutzerebene auf der Registerkarte Berechtigungen überschrieben werden können.',
        'help_groups' => 'Legen Sie fest, zu welchen Gruppen das Personal gehören soll. Durch Aufteilen von Agenten in Gruppen können Sie einfach Aufträge zuordnen.',
        'help_location' => 'Geben Sie an, zu welchen Standorten das Personal gehören soll. Das Personal kann NUR Menüs, Kategorien, Bestellungen, Reservierungen, Bewertungen und Gutscheine, die an den ausgewählten Standort(en) angehängt sind, ansehen. Gilt nicht für Super-Administratoren',
        'help_sale_permission_global_access' => 'Kann alle Bestellungen und Reservierungen im Admin-Bereich ansehen',
        'help_sale_permission_groups' => 'Kann Bestellungen und Reservierungen in ihrer Gruppe(n) und ihnen zugewiesenen Bestellungen und Reservierungen ansehen',
        'help_sale_permission_restricted' => 'Es können nur Bestellungen und Reservierungen angezeigt werden, die ihnen zugewiesen wurden',
    
        'alert_login_restricted' => 'Warning: You do not have the right permission to <b>access a staff account</b>, please contact system administrator.',
        'alert_impersonate_confirm' => 'Sind Sie sicher, dass Sie sich für dieses Personal ausgeben wollen? Sie können zu Ihrem ursprünglichen Status zurückkehren, indem Sie sich ausloggen.',
        'alert_impersonate_success' => 'Sie geben sich jetzt als Mitarbeiter aus: %s',
    ],

    'statuses' => [
        'text_title' => 'Status',
        'text_editor_title' => '%s hinzufügen',
        'text_form_name' => 'Status',
        'text_filter_status' => 'Alle Statustypen anzeigen',
        'text_empty' => 'Es gibt keine Statusdaten.',
        'text_order' => 'Bestellung',
        'text_reservation' => 'Reservierung',
        'text_unassigned' => 'Muss noch zugewiesen werden',
        'text_assigned_to_self' => 'Mir zugewiesen',
        'text_assigned_to_others' => 'Anderem Personal zugewiesen',

        'column_comment' => 'Status-Kommentar',
        'column_notify' => 'Benachrichtigung',
        'column_time_date' => 'Datum Zeit',
        'column_staff' => 'Mitarbeiter',
        'column_assignee' => 'Zugewiesen an',

        'label_for' => 'Status für',
        'label_color' => 'Farbe',
        'label_notify' => 'E-Mail-Benachrichtigung',
        'label_notify_customer' => 'Kunde informieren',
        'label_comment' => 'Kommentar',

        'label_assignee_group' => 'An Gruppe zuweisen',
        'label_assignee' => 'Dem Personal zuweisen',

        'help_notify' => 'Legen Sie fest, ob eine E-Mail an den Kunden gesendet wird, nachdem dieser Status auf die Bestellung gesetzt wurde. Diese Option kann von der Bestell-Bearbeitungsseite überschrieben werden.',
        'help_notify_customer' => 'Legen Sie fest, ob eine Statusaktualisierungs-E-Mail an den Kunden gesendet werden soll',

        'help_assignee_group' => 'Eine Benachrichtigung wird an alle Mitarbeiter der ausgewählten Gruppe gesendet',

        'alert_already_added' => 'Das ausgewählte %s muss sich von den aktuellen %s unterscheiden',
        'alert_invalid_action' => 'Ungültige Aktion.',
        'alert_status_not_found' => 'Status-ID [%s] nicht gefunden.',
    ],

    'stocks' => [
        'text_title' => 'Bestände',
        'text_form_name' => 'Bestand',
        'text_title_manage_stock' => 'Bestand verwalten',
        'text_title_stock_history' => 'Bestand Historie',
        'text_stock_description' => 'Verwaltung der Bestände für <b>%s</b> an %s Standort(en)',
        'text_empty' => 'Es sind keine Standorte verfügbar.',

        'button_manage_stock' => 'Bestand verwalten',
        'button_stock_history' => 'Bestand Historie',

        'text_action_none' => 'Grund auswählen',
        'text_action_in_stock' => '[+] Erhaltener Bestand',
        'text_action_restock' => '[+] Aufstockung',
        'text_action_recount' => '[=] Bestandsnachzählung',
        'text_action_sold' => '[-] Verkauft',
        'text_action_returned' => '[-] Zurückgeschickt',
        'text_action_waste' => '[-] Abfall',

        'label_is_tracked' => 'Bestand verfolgen',
        'label_quantity' => 'Lagerbestand Menge',
        'label_stock_action' => 'Bestand Aktion',
        'label_stock_quantity' => 'Bestand hinzufügen, entfernen oder nachzählen',
        'label_low_stock_alert' => 'Warnungen über niedrige Bestände',
        'label_low_stock_threshold' => 'Niedriger Schwellenwert',

        'column_staff_name' => 'Name Personal',
        'column_quantity' => 'Menge',
        'column_created_at' => 'Berechnet am',

        'help_is_tracked' => 'Wenn aktiviert, werden die Mengen der bestellten Menüs und/oder Optionen automatisch subtrahiert..',
        'help_low_stock_alert' => 'Aktivieren Sie automatische Warnungen bei niedrigem Lagerbestand, damit Sie E-Mails erhalten, wenn die Lagermenge unter den angegebenen Schwellenwert fällt oder diesem entspricht.',
    ],

    'tables' => [
        'text_title' => 'Tische',
        'text_form_name' => 'Tisch',
        'text_empty' => 'Es stehen keine Tische zur Verfügung.',
        'text_filter_search' => 'Suche nach Namen oder Kapazität.',

        'column_min_capacity' => 'Minimale Kapazität',
        'column_capacity' => 'Maximale Kapazität',
        'column_extra_capacity' => 'Zusätzliche Kapazität',
        'column_priority' => 'Priorität',
        'column_joinable' => 'Ist beitretbar',

        'label_min_capacity' => 'Minimale Kapazität',
        'label_capacity' => 'Maximale Kapazität',
        'label_extra_capacity' => 'Zusätzliche Kapazität',
        'label_priority' => 'Priorität',
        'label_joinable' => 'Ist beitretbar',

        'help_tables' => 'Wählen Sie einen Tische aus, um ihn diesem Ort hinzuzufügen.',
        'help_extra_capacity' => 'Das Personal verwendet intern um die Bequemlichkeit des Tisches zu bestimmen.',

        'error_capacity' => 'Der maximale Leistungswert muss größer sein als der Mindestkapazität.',
        'error_table_widget_data_not_specified' => 'Die Datenquelle des Tabellen-Widgets ist nicht in der Konfiguration angegeben.',
        'error_table_widget_data_class_not_found' => 'Die Datenquellenklasse des Tabellen-Widgets "%s" konnte nicht gefunden werden.',
    ],
];
