<?php

return [
    'text_tab_general' => 'Allgemein',
    'text_tab_texts' => 'Text',
    'text_info_heading' => 'Weitere Informationen über %s Restaurant',
    'text_gallery_heading' => 'Galerie von %s',
    'text_tab_delivery_order' => 'Liefermöglichkeiten',
    'text_tab_collection_order' => 'Optionen für die Abholung',

    'text_find' => 'Suchen',
    'text_order_summary' => 'Finden Sie ein Restaurant in Ihrer Nähe',
    'text_goto_menus' => 'Gehe zum Menü',
    'text_location_summary' => 'Wir können Ihnen %s liefern',
    'text_enter_location' => 'Überprüfen Sie, ob wir Ihnen liefern können',
    'text_hours' => 'Öffnungszeiten',
    'text_opening' => 'Öffnen',
    'text_24h' => 'Ganztägig',
    'text_delivery_coverage' => '<span class="text-danger">Sorry, aber dieses Restaurant liefert nicht an Ihren Standort</span>',
    'text_is_opened' => '<span class="text-success">Wir haben geöffnet</span>',
    'text_closed' => '<span class="text-close text-danger"> GESCHLOSSEN</span>',
    'text_is_closed' => '<span class="text-close text-danger">ist GESCHLOSSEN</span>',
    'text_opening_time' => 'Öffnet <b>%s</b>',
    'text_delivery_time_info' => 'Lieferung %s',
    'text_collection_time_info' => 'Abholung %s',
    'text_collection_time' => 'Abholzeit',
    'text_last_order_time' => 'Letzte Bestellzeit',
    'text_payments' => 'Zahlungen',
    'text_offer' => 'Leistungsangebot',
    'text_delivery_only' => 'Nur Lieferung',
    'text_collection_only' => 'Nur Abholung',
    'text_both_types' => 'Lieferung und Abholung verfügbar',
    'text_no_types' => 'Keine Lieferung oder Abholung verfügbar',
    'text_24_7_hour' => '24 Stunden, 7 Tage.',
    'text_single' => 'Einzeln',
    'text_multi' => 'Multi',
    'text_at' => 'at ',
    'text_starts' => ' startet %s',
    'text_condition_all_orders' => '{amount} Nachlass auf alle Bestellungen',
    'text_condition_above_total' => '{amount} über {total}',
    'text_condition_below_total' => '{amount} unter {total}',
    'text_delivery_areas' => 'Liefergebiete',
    'text_delivery_map' => 'Liefergebiet Karte',
    'text_working_hour' => '%s - %s',
    'text_min_total' => 'Mindestbestellwert',
    'text_no_min_total' => 'Kein Mindestbestellwert',

    'text_categories' => 'Kategorien',
    'text_all_categories' => 'Alle Kategorien',

    'text_delivery_is_disabled' => 'Delivery is not available.',
    'text_collection_is_disabled' => 'Pick-up is not available.',

    'text_locations_filter_title' => 'Filters',
    'text_filter_distance' => 'Entfernung',
    'text_filter_newest' => 'Neueste',
    'text_filter_rating' => 'Bewertung',
    'text_filter_search' => 'Nach Namen oder Ort suchen',
    'text_filter_no_match' => 'Kein Standort gefunden',

    'column_area_charge' => 'Lieferkosten',
    'column_area_min_total' => 'Mindestbestellwert',

    'column_language' => 'Sprache',
    'column_replace' => 'Ersetzen mit',

    'button_view_map' => 'Karte anzeigen',
    'button_change_location' => 'Standort ändern',
    'button_search_location' => 'Los!',
    'button_enter_location' => 'Standort eingeben',
    'button_view_menu' => 'Menü anzeigen',

    'label_default_order_type' => 'Standardmäßig ausgewählten Auftragstyp festlegen',
    'label_location_search_mode' => 'Standortsuche ausblenden',
    'label_hide_min_order_amount' => 'Kein Mindestbestellwert',
    'label_lang' => 'Sprachzeile',
    'label_status' => 'Status',
    'label_search_query' => 'Lieferadresse eingeben',
    'label_menu_search' => 'Menüeinträge suchen.',
    'label_redirect' => 'Seite zu der weitergeleitet werden soll, wenn kein Standort ausgewählt ist',
    'label_menu_page' => 'Menü Seite',
    'label_show_local_image' => 'Standort Thumbnail anzeigen',
    'label_local_image_height' => 'Standort Thumbnail Höhe',
    'label_local_image_width' => 'Standort Thumbnail Breite',

    'label_order_time' => '%s Zeit',
    'label_choose_order_time' => '%s Zeit festlegen',
    'label_date' => 'Datum auswählen',
    'label_time' => 'Zeit auswählen',
    'label_minute' => 'Minute',

    'label_limit_orders' => 'Anzahl Aufträge beschränken',
    'label_limit_orders_count' => 'Maximale Aufträge pro Intervall',
    'label_offer_delivery' => 'Lieferung anbieten',
    'label_offer_collection' => 'Abholung anbieten',
    'label_delivery_time_interval' => 'Zeitintervall der Lieferung',
    'label_collection_time_interval' => 'Zeitintervall der Abholung',
    'label_delivery_lead_time' => 'Vorlaufzeit der Lieferung',
    'label_collection_lead_time' => 'Vorlaufzeit für die Abholung',
    'label_future_delivery_order' => 'Vorbestellung zur Lieferung zulassen',
    'label_future_collection_order' => 'Vorbestellung zur Abholung zulassen',
    'label_future_delivery_days' => 'Max. Lieferung Vorbestellung Tage im Voraus',
    'label_future_collection_days' => 'Max. Abholung Vorbestellung Tage im Voraus',
    'label_future_min_delivery_days' => 'Min. Lieferung Vorbestellung Tage im Voraus',
    'label_future_min_collection_days' => 'Min. Abholung Vorbestellung Tage im Voraus',
    'label_delivery_cancellation_timeout' => 'Zeitlimit zur Stornierung der Lieferung',
    'label_collection_cancellation_timeout' => 'Zeitlimit zur Stornierung der Abholung',
    'label_delivery_time_restriction' => 'Einschränkung der Lieferfrist',
    'label_collection_time_restriction' => 'Einschränkung der Abholfrist',
    'label_delivery_add_lead_time' => 'Vorlaufzeit zur Startzeit der Lieferung hinzufügen',
    'label_collection_add_lead_time' => 'Vorlaufzeit zur Startzeit der Abholung hinzufügen',
    'label_delivery_min_order_amount' => 'Lieferung Mindestbestellwert',
    'label_collection_min_order_amount' => 'Abholung Mindestbestellwert',

    'help_location_search_mode' => 'Versteckt das lokale Suchformular. Um die lokale Suche vollständig im Schaufenster zu deaktivieren, <b>Bestellungsort anfordern</b> auf der Seite Bestell- & Reservierungseinstellungen abschalten.',
    'help_menu_page_limit' => 'Begrenzen Sie, wie viele Menüs pro Seite angezeigt werden',
    'help_show_menu_image' => 'Menübilder auf Ansichtsmenü-Seite anzeigen oder verstecken',

    'help_limit_orders' => 'Wenn Sie diese Option aktivieren, werden ASAP-Liefer- und Abholaufträge deaktiviert.',
    'help_limit_orders_interval' => 'Legen Sie die Anzahl der Bestellungen, zwischen den einzelnen Zeitfenstern.',
    'help_delivery_time_restriction' => 'Festlegen, ob Ihre Kunden nur Bestellungen für eine sofortige oder spätere Lieferung planen oder beides. Wenn die Vorbestellung aktiviert ist, gelten keine Beschränkungen.',
    'help_collection_time_restriction' => 'Festlegen, ob Ihre Kunden nur Bestellungen für die sofortige oder später Abholung planen oder beides. Wenn die Vorbestellung aktiviert ist, gelten keine Beschränkungen.',
    'help_delivery_time_interval' => 'Minuten festlegen, die Ihrem Kunden zwischen den einzelnen Lieferaufträgen zur Verfügung stehen.',
    'help_collection_time_interval' => 'Legen Sie die Minuten zwischen den einzelnen Abholaufträgen fest, die Ihrem Kunden zur Verfügung stehen.',
    'help_delivery_lead_time' => 'Legen Sie in Minuten fest, wie lange es im Durchschnitt dauert, bis eine Bestellung ausgeliefert wird, nachdem sie aufgegeben wurde.',
    'help_collection_lead_time' => 'Die durchschnittliche Zeit, die ein Auftrag nach seiner Erteilung benötigt, um abholbereit zu sein, wird in Minuten angegeben.',
    'help_delivery_cancellation_timeout' => 'Legt fest, wann ein Kunde einen Lieferauftrag nicht mehr stornieren kann. Anzahl der Minuten vor dem Liefertermin. Belassen Sie den Wert 0, um die Stornierung von Lieferaufträgen durch Kunden zu deaktivieren.',
    'help_collection_cancellation_timeout' => 'Legen Sie fest, wann ein Kunde einen Abholauftrag nicht mehr stornieren kann. Anzahl der Minuten vor der Abholzeit. Belassen Sie es bei 0, um die Stornierung von Abholaufträgen durch Kunden zu deaktivieren.',
    'help_delivery_add_lead_time' => 'Durch die Deaktivierung werden die Zeitfenster für die Zustellung ab der geplanten Öffnungszeit gestartet.',
    'help_collection_add_lead_time' => 'Durch die Deaktivierung werden die Abholzeitfenster ab der geplanten Öffnungszeit gestartet.',
    'help_delivery_min_order_amount' => 'Legen Sie den Mindestbetrag fest, den der Warenkorb eines Kunden erreichen muss, bevor er einen Lieferauftrag erteilen kann.',
    'help_collection_min_order_amount' => 'Legen Sie den Mindestbetrag fest, den der Warenkorb eines Kunden erreichen muss, bevor er einen Abholauftrag erteilen kann.',
    'help_future_delivery_days' => 'Legen Sie die Anzahl der Tage fest, die ein Kunde im Voraus zur Lieferung bestellen kann.',
    'help_future_collection_days' => 'Legen Sie die Anzahl der Tage fest, die ein Kunde im Voraus zur Abholung bestellen kann.',
    'help_future_min_delivery_days' => 'Legen Sie die Anzahl der Tage fest, die vergehen müssen, bevor ein Kunde zur Lieferung bestellen kann.',
    'help_future_min_collection_days' => 'Legen Sie die Anzahl der Tage fest, die vergehen müssen, bevor ein Kunde zur Abholung bestellen kann.',

    'alert_unknown_error' => 'Ein Fehler ist aufgetreten, bitte überprüfen und erneut versuchen.',
    'alert_no_search_setting' => 'Standortsuche nach Einstellung wurde nicht spezifiziert.',
    'alert_no_search_query' => 'Bitte geben Sie eine Adresse oder Postleitzahl ein, um zu prüfen, ob wir Sie beliefern können.',
    'alert_invalid_search_query' => 'We couldn\'t locate the entered address or postcode, please enter a valid address or postcode.',
    'alert_missing_street_address' => 'Bitte geben Sie Ihre Adresse ein.',
    'alert_no_found_restaurant' => 'Wir haben kein lokales Restaurant in Ihrer Nähe.',
    'alert_location_required' => 'Kein Standort gefunden oder ausgewählt',
    'alert_order_type_required' => 'Für diesen Standort gibt es keine aktive Online-Bestellmöglichkeit.',
    'alert_order_is_unavailable' => 'Dieses Restaurant kann zum gewählten Zeitpunkt keine Bestellungen von %s annehmen.',
    'alert_slot_time_required' => 'Bitte wählen Sie eine Zeitangabe aus.',
    'alert_slot_date_required' => 'Bitte wählen Sie ein Datum.',
    'alert_slot_type_required' => 'Bitte wählen Sie einen Typ.',
    'alert_max_guest_reached' => 'Wir haben die maximale Anzahl von Aufträgen für das ausgewählte Zeitfenster erreicht, bitte wählen Sie ein anderes Zeitfenster.',

    'component_title' => 'Lokale Box Komponente',
    'component_desc' => 'Lokale Informations Box anzeigen',
    'text_heading' => 'Restaurants',
    'text_local_heading' => '%s - Restaurant',
    'text_delivery_time' => 'Lieferzeit',
    'text_from' => ' Von ',
    'text_on' => ' am ',
    'text_source' => 'Quellen Titel',
    'text_delivery' => 'Lieferung',
    'text_collection' => 'Abholung',
    'text_no_delivery_areas' => 'Kein Lieferbereich abgedeckt.',
    'text_asap' => 'Schnellstmöglich',
    'text_later' => 'Bestellung planen',
    'text_none' => 'Keine',
    'text_in_min' => 'in %s Minuten',
    'text_in_minutes' => 'in <b>%s</b> Minuten',
    'text_after_opening' => '<b>%s</b> Minuten, nachdem wir öffnen',
    'text_same_as_opening_hours' => 'Identisch mit Öffnungszeiten',
    'text_delivery_all_orders' => 'auf alle Bestellungen',
    'text_delivery_not_available' => 'Lieferung ist nicht verfügbar',
    'text_miles' => 'Meilen',
    'text_kilometers' => 'Kilometer',

    'text_filter' => 'Hinweis: Filtern Sie das Menü, indem Sie eine Kategorie auf der linken Seite auswählen',
    'text_empty' => 'Kein Menüpunkt gefunden.',
    'text_no_category' => 'Kein Menüpunkt in dieser Kategorie gefunden.',
    'text_empty_gallery' => 'Keine Bilder zum Anzeigen.',
    'text_no_match' => 'Es wurden keine Artikel gefunden, die der ausgewählten Kategorie entsprechen.',
    'text_hungry' => 'Hungrig?',
    'text_category' => 'Menükategorie',
    'text_specials' => 'Spezielle Angebote',
    'text_end_days' => 'Endet %s in %s Tagen',
    'text_end_today' => 'Endet heute',
    'text_end_elapsed' => 'Endet in %s',
    'text_mealtime' => 'Verfügbar während %s (%s - %s)',
    'text_price_form' => 'Ab %s',

    'text_settings' => 'Bewertungseinstellungen',
    'text_settings_description' => 'lokale Bewertungen einstellen',

    'search' => [
        'component_title' => 'Lokale Suchkomponente',
        'component_desc' => 'Zeigt ein eigenständiges lokales Suchformular an',

        'text_change' => 'ändern',
        'text_saved_addresses' => 'Saved addresses',
    ],

    'menu' => [
        'component_title' => 'Lokale Menükomponente',
        'component_desc' => 'Zeigt eine Liste von lokalen Menüeinträgen an',
    ],

    'categories' => [
        'component_title' => 'Lokale Kategorie-Komponente',
        'component_desc' => 'Zeigt eine Liste von lokalen Menükategorien an',
    ],

    'review' => [
        'component_title' => 'Lokale Bewertungs Komponente',
        'component_desc' => 'Zeigt eine Liste von lokalen Bewertungen an',
        'text_review_heading' => 'Kundenbewertungen von %s',
        'text_total_review' => '(%s)',
        'text_no_review' => 'Es gibt noch keine Bewertungen.',
        'text_your_review' => 'Ihre Bewertung',
        'text_write_review' => 'Hat es Ihnen geschmeckt?',

        'label_quality' => 'Qualität',
        'label_delivery' => 'Lieferung',
        'label_service' => 'Service',
        'label_review' => 'Bewertung',
        'label_date' => 'Bewertungsdatum',

        'button_review' => 'Bewertung senden',

        'alert_review_disabled' => 'Bewertungen wurden deaktiviert, bitte wenden Sie sich an den Administrator.',
        'alert_review_success' => 'Überprüfung erfolgreich versendet, wird nach Freigabe sichtbar.',
        'alert_review_error' => 'Ein Fehler ist aufgetreten, bitte versuchen Sie es erneut.',
        'alert_review_duplicate' => 'Entschuldigung. Entweder hast du bereits eine Bewertung für diese Bestellung hinterlassen oder ein Fehler ist aufgetreten.',
        'alert_review_status_history' => 'Bewertung kann nicht hinzugefügt werden, da Bestellung/Reservierung nicht abgeschlossen ist',
    ],

    'info' => [
        'component_title' => 'Lokale Info-Komponente',
        'component_desc' => 'Lokale Informations Box anzeigen',
    ],

    'gallery' => [
        'component_title' => 'Lokale Galerie-Komponente',
        'component_desc' => 'Lokale Bilder anzeigen',
    ],

    'list' => [
        'component_title' => 'Lokale Listen Komponente',
        'component_desc' => 'Zeigt eine Liste von Standorten an',
    ],

    'reviews' => [
        'side_menu' => 'Bewertungen',
        'permissions' => 'Benutzerbewertungen verwalten',

        'text_title' => 'Bewertungen',
        'text_form_name' => 'Bewertung',
        'text_empty' => 'Es gibt keine Bewertungen.',
        'text_filter_search' => 'Suchen Sie nach Autor, Restaurant oder Verkaufs-Id.',
        'text_pending_review' => 'Warte auf Überprüfung',
        'text_approved' => 'Genehmigt',
        'text_order' => 'Bestellung',
        'text_reservation' => 'Reservierung',

        'text_settings' => 'Bewertungseinstellungen',
        'text_settings_description' => 'Einstellungen für Bewertungen aktivieren/deaktivieren und konfigurieren',

        'text_chase_email' => 'Review chase email to customer',

        'column_location' => 'Standort',
        'column_author' => 'Autor',
        'column_sale_id' => 'Verkauf-ID',
        'column_sale_type' => 'Verkaufsart',
        'column_text' => 'Bewertungstext',

        'label_sale_type' => 'Verkaufsart',
        'label_sale_id' => 'Verkauf-ID',
        'label_location' => 'Standort',
        'label_customer' => 'Kunde',
        'label_author' => 'Autor',
        'label_quality' => 'Qualitätsbewertung',
        'label_delivery' => 'Lieferbewertung',
        'label_service' => 'Service-Bewertung',
        'label_text' => 'Bewertungstext',
        'label_hints' => 'Bewertungshinweise',

        'label_allow_reviews' => 'Bewertungen erlauben',
        'label_approve_reviews' => 'Bewertungen genehmigen',
        'label_chase_reviews' => 'Chase Reviews',
        'label_chase_reviews_after' => 'Chase after how many hours?',

        'text_tab_title_reviews' => 'Bewertungen',

        'help_allow_reviews' => 'Neuen Kundenbewertungseintrag und Anzeige von Bewertungen im Schaufenster aktivieren oder deaktivieren',
        'help_approve_reviews' => 'Neuen Eintrag automatisch oder manuell genehmigen',
        'help_hints' => 'Wird beim Hinzufügen von Bewertungen verwendet.',
        'help_chase_reviews' => 'Send a follow up email when a review has not been submitted',

        'error_not_found_in_order' => 'Die eingegebene Verkaufs-ID kann in Bestellungen nicht gefunden werden',
        'error_not_found_in_reservation' => 'Die eingegebene Verkaufs-ID kann nicht in Reservierungen gefunden werden',
    ],
];
