<?php

return [
    'text_title' => 'Küchenanzeige',
    'text_form_name' => 'Ansicht',

    'column_id' => 'ID',
    'column_time' => 'Zeit',
    'column_name' => 'Name',
    'column_phone' => 'Telefon',
    'column_comments' => 'Kommentare',
    'column_order' => 'Bestellung',
    'column_total' => 'Summe',
    'column_status' => 'Status',

    'comment_ordersforXhours' => '0 bedeutet keine Grenzen',
    'comment_limitUsers' => 'Keine Auswahl bedeutet keine Einschränkungen',

    'btn_view' => 'Ansicht',
    'btn_prep' => 'Vorbereitung',
    'btn_ready' => 'Bereit',
    'btn_complete' => 'Abschließen',

    'label_name' => 'Name',
    'label_status' => 'Status',
    'label_locations' => 'Bestellungen von Standorten',
    'label_categories' => 'Menüpunkte aus Kategorien anzeigen',
    'label_ordertypes' => 'Art der Bestellungen',
    'label_order_status' => 'Bestellungen mit ausgewähltem Status',
    'label_order_assigned' => 'Bestellungen zugewiesen an',
    'label_ordercount' => 'Anzahl der anzuzeigenden Bestellungen',
    'label_refreshinterval' => 'Aktualisierungsintervall in Sekunden',
    'label_ordersforXhours' => 'Auf die nächsten X Stunden der Bestellungen begrenzen',
    'label_limitUsers' => 'Zugriff auf ausgewählte Benutzer beschränken',

    'label_button1_enabled' => 'Button 1 aktiviert',
    'label_button1_text' => 'Button 1 Text',
    'label_button1_status' => 'Button 1 Status',
    'label_button1_color' => 'Button 1 Hintergrundfarbe',
    'label_button2_enabled' => 'Button 2 aktiviert',
    'label_button2_text' => 'Button 2 Text',
    'label_button2_status' => 'Button 2 Status',
    'label_button2_color' => 'Schaltfläche 2 Hintergrundfarbe',
    'label_button3_enabled' => 'Schaltfläche 3 aktiviert',
    'label_button3_text' => 'Button 3 Text',
    'label_button3_status' => 'Schaltfläche 3 Status',
    'label_button3_color' => 'Schaltfläche 3 Hintergrundfarbe',

    'label_card_line_1' => 'Linie 1 Layout',
    'label_card_line_2' => 'Linie 2 Layout',
    'label_card_line_3' => 'Linie 3 Layout',
    'label_card_status' => 'Status anzeigen',
    'label_card_items' => 'Menüeinträge anzeigen',
    'label_card_assign' => 'Zuweisung anzeigen',
    'label_card_print' => 'Show print',

    'option_blank' => 'Leer',
    'option_name_id' => 'Name / Bestell-Nr.',
    'option_id_name' => 'Bestell-Nr. / Name',
    'option_time_phone_total' => 'Zeit / Telefon / Gesamt',
    'option_phone_time_total' => 'Telefon / Zeit / Gesamt',
    'option_time_phone_total_code' => 'Zeit / Telefon / Gesamt / Zahlungscode',
    'option_phone_time_total_code' => 'Telefon / Zeit / Gesamt / Zahlungscode',
    'option_datetime_phone_total' => 'Datum und Zeit / Telefon / Gesamt',
    'option_phone_datetime_total' => 'Telefon / Datum und Zeit / Gesamt',
    'option_datetime_phone_total_code' => 'Datum und Zeit / Telefon / Gesamt / Zahlungscode',
    'option_phone_datetime_total_code' => 'Telefon / Datum / Zeit / Gesamt / Zahlungscode',
    'option_address' => 'Adresse',
    'option_address_maps_bing' => 'Adresse + Google Maps + Bing',
    'option_address_maps' => 'Adresse + Google Maps',
    'option_address_bing' => 'Adresse + Bing',

    'tab_general' => 'Allgemein',
    'tab_buttons' => 'Buttons',
    'tab_cards' => 'Karten',

    'text_empty' => 'Keine Ansichten zum anzeigen',

    'value_anyone' => 'Jeder',
    'value_all_orders' => 'Alle Bestellungen',
    'value_delivery' => 'nur Lieferung',
    'value_collection' => 'Nur Abholung',

];
