<?php

return [
    'system_name' => 'TastyIgniter',
    'system_powered' => '<a target="_blank" href="http://tastyigniter.com">Powered by TastyIgniter</a>',
    'copyright' => 'Vielen Dank für die Verwendung <a target="_blank" href="http://tastyigniter.com">TastyIgniter</a>',
    'version' => '<b>Version:</b> %s',

    'no_database' => [
        'label' => 'Datenbankfehler wurde zusammengefasst',
        'help' => 'Eine Datenbankverbindung ist erforderlich. Überprüfen Sie das die Datenbank korrekt konfiguriert und migriert, bevor Sie es erneut versuchen.',
    ],
    'required' => [
        'config' => "Konfiguration, die in %s verwendet wird, muss einen Wert '%s ' angeben.",
    ],
    'not_found' => [
        'model' => "Das Modell ':name' wurde nicht gefunden.",
        'layout' => "Das Layout ':name' wurde nicht gefunden.",
        'partial' => "Der partielle ':name' wurde nicht gefunden.",
        'config' => 'Konfigurationsdatei %s konnte nicht gefunden werden, die für %s definiert ist.',
        'class' => "Kann '%s' in %s' nicht finden",
        'combiner' => "Kann keine Assets '%s 'finden",
    ],
    'missing' => [
        'config_key' => 'Fehlender benötigter [%s] Schlüssel in [%s]',
        'carte_key' => 'Kein Carte-Schlüssel gefunden, klicken Sie auf die Schaltfläche unten, um einen einzugeben.',
    ],
    'error' => [
    ],

    'date' => [
        'today' => 'Heute',
        'tomorrow' => 'Morgen',
        'yesterday' => 'Gestern',
        'full' => '%s at %s',
    ],

    'php' => [
        'date_format' => 'd M Y',
        'date_format_short' => 'd M',
        'date_format_long' => 'l, jS F Y',
        'time_format' => 'H:i',
        'date_time_format' => 'd M Y H:i',
        'date_time_format_short' => 'd M H:i',
        'date_time_format_long' => 'l, jS F Y \a\t h:i a',
    ],

    'moment' => [
        'date_format' => 'DD MMM YYYY',
        'date_format_short' => 'DD MMM',
        'date_format_long' => 'dddd, Do MMM YYYY',
        'time_format' => 'hh:mm a',
        'date_time_format' => 'DD MMMM YYYY HH:mm',
        'date_time_format_short' => 'DD MMM \a\t HH:mm',
        'date_time_format_long' => 'dddd, Do MMMM YYYY \a\t HH:mm a',
        'day_format' => 'ddd DD',
        'day_time_format' => 'ddd DD hh:mm a',
        'day_time_format_short' => 'ddd hh:mm a',
    ],

    'activities' => [
        'text_title' => 'Aktivitäten',
        'button_mark_as_read' => 'Alle als gelesen markieren',
        'text_empty' => 'Es stehen keine Aktivitäten zur Verfügung.',
        'activity_system' => 'System',
        'activity_self' => 'Sie',
        'activity_master_logged_in' => ' <b>hat</b> als <b>:subject.first_name :subject.last_name</b> geloggt.',
    ],

    'countries' => [
        'text_title' => 'Länder',
        'text_form_name' => 'Land',
        'text_filter_search' => 'Suche nach Name oder Code.',
        'text_empty' => 'Keine Länder verfügbar.',

        'column_iso_code2' => 'ISO-Code 2',
        'column_iso_code3' => 'ISO-Code 3',
        'column_status' => 'Status',

        'label_priority' => 'Priorität',
        'label_format' => 'Format',
        'label_iso_code2' => 'ISO-Code 2',
        'label_iso_code3' => 'ISO-Code 3',

        'help_format' => 'Adresse 1 = {address_1}<br/>Adresse 2 = {address_2}<br/>Stadt = {city}<br/>Postleitzahl = {postcode}<br/>Staat = {state}<br/>Land = {country}',
        'help_iso' => 'Erfahren Sie mehr über <a target="_blank" href="http://en.wikipedia.org/wiki/ISO_3166-1">ISO Alpha 2 & 3</a>',
    ],

    'currencies' => [
        'text_title' => 'Währungen',
        'text_form_name' => 'Währung',
        'text_filter_search' => 'Suche nach Name oder Code.',
        'text_empty' => 'Keine Währung verfügbar.',
        'text_right' => 'Rechts',
        'text_left' => 'Links',

        'column_code' => 'Code',
        'column_country' => 'Land',
        'column_symbol' => 'Symbol',
        'column_rate' => 'Bewertung',
        'column_status' => 'Status',

        'label_title' => 'Titel',
        'label_code' => 'Code',
        'label_country' => 'Land',
        'label_symbol' => 'Symbol',
        'label_symbol_position' => 'Symbol position',
        'label_rate' => 'Bewertung',
        'label_thousand_sign' => 'Tausender-Trennzeichen',
        'label_decimal_sign' => 'Dezimatrennzeichen',
        'label_decimal_position' => 'Dezimalstelle',

        'help_iso' => 'Erfahren Sie mehr über <a target="_blank" href="https://en.wikipedia.org/wiki/ISO_4217">ISO 4217</a>',
    ],

    'extensions' => [
        'text_title' => 'Erweiterungen',
        'text_delete_title' => 'Erweiterung: löschen',
        'text_filter_search' => 'Suche nach Namen.',
        'text_empty' => 'Es gibt keine Erweiterungen zur Verfügung.',
        'text_installed' => 'Installiert',
        'text_uninstalled' => 'Deinstalliert',
        'text_files' => 'Dateien',
        'text_files_data' => 'Dateien und Daten',
        'text_settings' => 'Einstellungen',
        'text_author' => 'Autor',

        'button_browse' => '<i class="fa fa-globe"></i>&nbsp;&nbsp;Weitere Erweiterungen durchsuchen',
        'button_check' => '<i class="fa fa-refresh"></i>&nbsp;&nbsp;Updates',
        'button_delete' => 'Löschen',
        'button_payments' => 'Zahlungen verwalten',
        'button_settings' => 'Einstellungen verwalten',
        'button_yes_delete' => 'Ja, löschen',
        'button_return_to_list' => 'Nein, zurück zur Liste',

        'column_icon' => 'Icon',
        'column_version' => 'Version',

        'label_delete_data' => 'Daten löschen',

        'error_config_no_found' => 'Ein Fehler ist aufgetreten, die Registrierungsdatei der Erweiterung konnte nicht gefunden werden',

        'alert_info_layouts' => '<b>Layout & Seitenkomponente(n) registriert</b>',
        'alert_warning_layouts' => 'Um die Komponente für diese Erweiterung auf einer Seite anzuzeigen, fügen Sie sie <a href="%s" class="alert-link">hier </a>einem Layout hinzu!',
        'alert_delete_warning' => 'Sie sind dabei, %s der Erweiterung <b>%s</b> zu löschen',
        'alert_delete_confirm' => 'Sind Sie sicher, dass Sie die zugehörige %s löschen möchten? Dies kann nicht rückgängig gemacht werden!',
        'alert_is_installed' => '. Sie müssen eine Erweiterung deinstallieren, bevor Sie sie löschen.',
        'alert_setting_missing_id' => 'Der Erweiterungs-Einstellungscode wurde nicht angegeben.',
        'alert_setting_not_found' => 'Erweiterungseinstellungen wurden nicht gefunden.',
        'alert_setting_model_missing' => 'Fehlendes Einstellungsmodell.',
        'alert_setting_model_not_found' => 'Modell der Erweiterungseinstellungen [%s] wurde nicht gefunden.',
    ],

    'languages' => [
        'text_title' => 'Sprachen',
        'text_form_name' => 'Sprache',
        'text_tab_general' => 'Details',
        'text_tab_files' => 'Übersetzungen',
        'text_tab_edit_file' => 'Übersetzung bearbeiten',
        'text_filter_search' => 'Suche nach Namen.',
        'text_filter_file' => 'Alle Übersetzungen anzeigen',
        'text_filter_translations' => 'Übersetzungen filtern.',
        'text_empty' => 'Es sind keine Sprachen verfügbar.',
        'text_empty_translations' => 'Es sind keine Übersetzungen verfügbar.',
        'text_files' => 'Dateien',
        'text_locale_strings' => 'Sprachzeichenketten (%s%% übersetzt, %s Zeichenketten)',

        'column_code' => 'Code',
        'column_status' => 'Status',
        'column_variable' => 'Quelltext (Englisch)',
        'column_language' => 'Übersetzungstext (%s)',

        'label_code' => 'Locale Code',
        'label_image' => 'Icon',
        'label_idiom' => 'Dialekt',

        'button_new' => 'Neue Gruppe',

        'help_language' => 'Verwenden Sie einen vollständigen Locale-Code (z.B. „fr_FR“) statt nur einen generischen Sprachcode (z.B. „fr“) dieser muss mit dem Locale Verzeichnis auf dem Webserver identisch sein.',

        'alert_save_changes' => 'Ihre Änderungen gehen verloren, wenn Sie sie nicht speichern, bevor Sie eine andere Sprachdatei bearbeiten.',

        'translations' => [

            'label_file' => 'Locale Datei',
            'label_search' => 'Suchen',

            'help_no_files' => 'Keine passenden Übersetzungen für diese Sprache gefunden. Sie müssen ein Sprachpaket installieren.',
        ],
    ],

    'mail_templates' => [
        'text_title' => 'Mail-Layouts',
        'text_form_name' => 'Mail-Layout',
        'text_template_title' => 'E-Mail-Vorlagen',
        'text_new_template_title' => 'E-Mail Vorlage: Neu',
        'text_edit_template_title' => 'E-Mail-Vorlage: Aktualisieren',
        'text_preview_template_title' => 'E-Mail-Vorlage: Vorschau',
        'text_partial_title' => 'Mail Partials',
        'text_partial_form_name' => 'Mail Partial',
        'text_new_partial_title' => 'Mail Partials: Neu',
        'text_edit_partial_title' => 'Mail Partials: Aktualisieren',
        'text_preview_partial_title' => 'Mail Partials: Vorschau',
        'text_templates' => 'Templates',
        'text_layouts' => 'Layouts',
        'text_partials' => 'Partials',
        'text_empty' => 'Es sind keine Mail-Vorlagen verfügbar.',
        'text_variables' => 'Variablen',
        'text_registration' => 'Registrierungs-E-Mail an Kunden',
        'text_password_reset_request' => 'Kennwort zurücksetzen e-Mail an Kunden',
        'text_password_reset_request_alert' => 'Kennwort zurücksetzen e-Mail an admin',
        'text_password_reset' => 'Kennwort zurücksetzen e-Mail an Kunden',
        'text_password_reset_alert' => 'Kennwort zurücksetzen e-Mail an admin',
        'text_order' => 'Bestell-Email an Kunden',
        'text_reservation' => 'Reservierung e-Mail an Kunden',
        'text_internal' => 'Interne Meldung',
        'text_contact' => 'Kontakt per e-Mail an admin',
        'text_registration_alert' => 'Registrierungs-Benachrichtigung E-Mail an Admin',
        'text_order_alert' => 'Bestell-Alarm-E-Mail an Admin',
        'text_reservation_alert' => 'Reservierungs-Warnung an Admin',
        'text_order_update' => 'Bestellstatus-Update-E-Mail an Kunden',
        'text_reservation_update' => 'Reservierungsstatus Update E-Mail an Kunden',

        'button_test_message' => 'Testnachricht senden',

        'column_code' => 'Code',
        'column_title' => 'Titel',
        'column_layout' => 'Layout',
        'column_status' => 'Status',

        'label_language' => 'Sprache',
        'label_code' => 'Code',
        'label_subject' => 'Betreff',
        'label_layout' => 'Layout',
        'label_layout_css' => 'Layout - CSS',
        'label_body' => 'HTML',
        'label_markdown' => 'Markdown',
        'label_plain' => 'Nur Text',

        'help_variables' => 'Ziehen Sie diese Variablen in den Inhaltsbereich:',

        'alert_test_message_sent' => 'Testnachricht erfolgreich gesendet an %s',
    ],

    'mail_variables' => [
        'text_group_global' => 'Globale Variablen',
        'text_site_name' => 'Seitenname',
        'text_site_logo' => 'Seitenlogo',

        'text_group_customer' => 'Kundenvariablen',
        'text_first_name' => 'Vorname des Kunden',
        'text_last_name' => 'Nachname des Kunden',
        'text_email' => 'E-Mail-Adresse des Kunden',
        'text_telephone' => 'Kunden-Telefonadresse',

        'text_group_staff_reset' => 'Personal-Passwort zurücksetzen Variablen',
        'text_staff_name' => 'Mitarbeitername',
        'text_staff_reset_link' => 'Mitarbeiter Kennwort-URL zurücksetzen',

        'text_group_registration' => 'Registrierungsvariablen',
        'text_account_login_link' => 'Account-Login-URL',

        'text_group_reset' => 'Passwort zurücksetzen Variablen',
        'text_reset_code' => '
Passwortzurücksetzungscode',
        'text_reset_link' => 'Passwort zurücksetzen URL',

        'text_group_order' => 'Bestellvariablen',
        'text_order_number' => 'Bestellnummer',
        'text_customer_name' => 'Vollständiger Kundenname',
        'text_order_type' => 'Bestellart z.B. Lieferung/Abholung',
        'text_order_time' => 'Lieferzeit/Abholzeit',
        'text_order_date' => 'Bestellung/Abholdatum',
        'text_order_added' => 'Erstellungsdatum der Bestellung',
        'text_order_payment' => 'Bestell-Zahlungsmethode',
        'text_order_address' => 'Kundenadresse für Lieferauftrag',
        'text_invoice_number' => 'Kunden-Telefonadresse',
        'text_invoice_date' => 'Kunden-Telefonadresse',
        'text_order_menus' => 'Array von Bestellmenüelementen',
        'text_order_comment' => 'Bestellkommentar',
        'text_location_name' => 'Standortname',
        'text_location_email' => 'Standort E-Mail',
        'text_location_address' => 'Standort-Adresse',
        'text_order_view_url' => 'Bestellansicht-URL',
        'text_order_totals' => 'Array der Auftragssummen',
        'text_menu_name' => 'Name des Bestellmenüs',
        'text_menu_quantity' => 'Bestellmenü-Menge',
        'text_menu_price' => 'Bestellmenüpreis',
        'text_menu_subtotal' => 'Bestellmenü-Zwischensumme',
        'text_menu_options' => 'Bestellmenüoption z.B.: Preis',
        'text_menu_comment' => 'Bestellmenükommentar',
        'text_order_total_title' => 'Auftragssumme Titel',
        'text_order_total_value' => 'Summe aller Bestellungen',
        'text_priority' => 'Bestellung total Priorität',

        'text_group_reservation' => 'Reservierungsvariablen',
        'text_reservation_number' => 'Reservierungsnummer',
        'text_reservation_date' => 'Reservierungsdatum',
        'text_reservation_time' => 'Reservierungszeit',
        'text_reservation_guest_no' => 'Anzahl der reservierten Gäste',
        'text_reservation_comment' => 'Reservierungskommentar',
        'text_reservation_view_url' => 'Reservierungsansicht URL',

        'text_status_name' => 'Statusname',
        'text_status_comment' => 'Statuskommentar',

        'text_group_contact' => 'Kontaktvariablen',
        'text_full_name' => 'Name des Kontakts',
        'text_contact_email' => 'Kontakt-E-Mail',
        'text_contact_telephone' => 'Kontakt Telefon',
        'text_contact_topic' => 'Kontaktthema',
        'text_contact_message' => 'Text der Kontaktnachricht',

    ],

    'permissions' => [
        'name' => 'System',
        'activities' => 'Zugriffsaktivitäten',
        'countries' => 'Länder erstellen, bearbeiten und löschen',
        'currencies' => 'Währungen erstellen, bearbeiten und löschen',
        'system_logs' => 'System- und Anfrage-Logs anzeigen',
        'extensions' => 'Erweiterung installieren, deinstallieren und löschen',
        'mail_templates' => 'Mail-Vorlagen erstellen, bearbeiten und löschen',
        'languages' => 'Website-Sprachen erstellen, bearbeiten und löschen',
        'settings' => 'Systemeinstellungen verwalten',
        'updates' => 'Möglichkeit, Updates anzuwenden, wenn eine neue Version von TastyIgniter verfügbar ist',
    ],

    'request_logs' => [
        'text_title' => 'Anfragenverlauf',
        'text_form_name' => 'Anfragenverlauf',
        'text_filter_search' => 'Suche nach Namen.',
        'text_empty' => 'Es sind keine Request-Logs verfügbar.',
        'text_empty_referrer' => 'Es gibt keine Verweise auf diese URL.',

        'column_status_code' => 'Statuscode',
        'column_url' => 'Angeforderte Url',
        'column_count' => 'Zähler',

        'label_url' => 'Angeforderte Url',
        'label_referer' => 'Referrer',
    ],

    'settings' => [
        'text_title' => 'Einstellungen',
        'text_edit_title' => 'Einstellungen: %s',
        'text_tab_general' => 'Allgemein',
        'text_tab_restaurant' => 'Restaurant',
        'text_tab_mail' => 'E-Mail',
        'text_tab_server' => 'Erweitert',

        'text_tab_desc_general' => 'Ändern Sie Ihren Restaurantnamen, E-Mail und Url, Standardsprache, Währung und Datumsformat, ...',
        'text_tab_desc_mail' => 'Einstellungen für das Versenden von E-Mails',
        'text_tab_desc_server' => 'Verwalten Sie erweiterte Systemeinstellungen wie Aktivieren/Deaktivieren des Wartungsmodus.',

        'text_tab_site' => 'Seite',
        'text_tab_title_maps' => 'Geolokalisierung',
        'text_tab_title_date_time' => 'Datum/Zeit',
        'text_tab_title_currency' => 'Währung',
        'text_tab_title_language' => 'Sprache',
        'text_tab_title_taxation' => 'Besteuerung',
        'text_tab_title_invoice' => 'Rechnungsstellung',
        'text_tab_title_order' => 'Bestellung',
        'text_tab_title_reservation' => 'Reservierung',
        'text_tab_title_maintenance' => 'Wartungsarbeiten',
        'text_tab_title_system_log' => 'Log-Einstellungen',
        'text_tab_title_activity_log' => 'Aktivitätsprotokolleinstellungen',
        'text_single' => 'Einzeln',
        'text_multiple' => 'Mehrere',
        'text_1_hour' => '1 Stunde',
        'text_3_hours' => '3 Stunden',
        'text_6_hours' => '6 Stunden',
        'text_12_hours' => '12 Stunden',
        'text_24_hours' => '24 Stunden',
        'text_3_days' => '3 Tage',
        'text_5_days' => '5 Tage',
        'text_1_week' => '1 Woche',
        'text_auto' => 'Automatisch',
        'text_manual' => 'Manuell',
        'text_miles' => 'Meilen',
        'text_kilometers' => 'Kilometer',
        'text_chain_geocoder' => 'Chain (empfohlen)',
        'text_google_geocoder' => 'Google Geocoding',
        'text_nominatim' => 'OpenStreetMap\'s Nominatim',
        'text_plain' => 'Nur Text',
        'text_html' => 'HTML',
        'text_sendmail' => 'Sendmail',
        'text_smtp' => 'SMTP',
        'text_log_file' => 'Log Datei',
        'text_mailgun' => 'Mailgun',
        'text_postmark' => 'Postmark (erfordert die Drittanbieter-Treiber-Erweiterung)',
        'text_ses' => 'SES',
        'text_mail_no_encryption' => 'Keine Verschlüsselung',
        'text_mail_tls_encryption' => 'TLS',
        'text_mail_ssl_encryption' => 'SSL',
        'text_to_customer' => 'An Kunden',
        'text_to_admin' => 'An Restaurant',
        'text_to_location' => 'An Standort',
        'text_send_test_email' => 'Test E-Mail senden',
        'text_internal_sequence_prefix' => 'Präfix plus interne Nummerierung',
        'text_menu_price_include_tax' => 'Menüpreise enthalten bereits die Mehrwertsteuer',
        'text_apply_tax_on_menu_price' => 'Steuer auf meinen Menüpreis anwenden',
        'text_openexchangerates' => 'Open Exchange Rates',
        'text_fixerio' => 'Fixer.io',

        'label_site_name' => 'Restaurantname',
        'label_site_email' => 'Restaurant-E-Mail',
        'label_site_logo' => 'Restaurant-Logo',
        'label_timezone' => 'Standard-Zeitzone',
        'label_site_currency' => 'Standardwährung',
        'label_currency_converter' => 'Standard Währungsumrechner',
        'label_currency_converter_oer_api_key' => 'Währungsumrechner (Open Exchange Rate API) App ID',
        'label_currency_converter_fixer_api_key' => 'Währungswandler (Fixer.io API) App ID',
        'label_currency_refresh_interval' => 'Aktualisierungsintervall der Wechselkurse',
        'label_detect_language' => 'Browsersprache erkennen',
        'label_site_language' => 'Standardsprache',
        'label_customer_group' => 'Kundegruppe',
        'label_country' => 'Land',
        'label_maps_api_key' => 'Google Maps-API-Schlüssel',
        'label_distance_unit' => 'Entfernungseinheit',
        'label_default_geocoder' => 'Standard Geocoder',
        'label_tax_mode' => 'Steuer-Modus',
        'label_tax_title' => 'Steuer-Titel',
        'label_tax_percentage' => 'Steuersatz',
        'label_tax_menu_price' => 'Steuer-Menüpreis',
        'label_tax_delivery_charge' => 'Steuer-Versandkosten',
        'label_default_order_status' => 'Standard-Bestellstatus',
        'label_processing_order_status' => 'Verarbeitung-Bestellstatus',
        'label_completed_order_status' => 'Status <b style="color: green;">Abgeschlossen</b>',
        'label_canceled_order_status' => 'Stornierung-Bestellstatus',
        'label_menus_page' => 'Menü Artikel Seite',
        'label_guest_order' => 'Gastbestellung erlauben',
        'label_location_order' => 'Aufträge außerhalb des Lieferbereichs ablehnen',
        'label_invoice_prefix' => 'Rechnung-Präfix',
        'label_default_reservation_status' => 'Standardstatus Reservierung',
        'label_confirmed_reservation_status' => 'Bestätigte Reservierungsstatus',
        'label_canceled_reservation_status' => 'Stornierte Reservierungsstatus',
        'label_media_max_size' => 'Maximale Dateigröße',
        'label_media_thumb_height' => 'Miniaturansicht Höhe',
        'label_media_thumb_width' => 'Miniaturansicht breite',
        'label_media_uploads' => 'Uploads',
        'label_media_new_folder' => 'Neuer Ordner',
        'label_media_copy' => 'Kopieren',
        'label_media_move' => 'Verschieben',
        'label_media_rename' => 'Umbenennen',
        'label_media_delete' => 'Löschen',
        'label_media_transliteration' => 'Transliteration',
        'label_allow_registration' => 'Kundenregistrierung erlauben',
        'label_registration_email' => 'Registrierungs-E-Mail senden',
        'label_order_email' => 'Bestellbestätigung/Alarm-E-Mail senden',
        'label_reservation_email' => 'Reservierungsbestätigung/Alarm-E-Mail senden',
        'label_sender_name' => 'Absender-Name',
        'label_sender_email' => 'Absender Email',
        'label_protocol' => 'Mail-Protokoll',
        'label_sendmail_path' => 'Sendmail-Pfad',
        'label_smtp_host' => 'SMTP-Host',
        'label_smtp_port' => 'SMTP-Port',
        'label_smtp_user' => 'SMTP-Benutzername',
        'label_smtp_pass' => 'SMTP Kennwort',
        'label_smtp_encryption' => 'Verschlüsselungsprotokoll',
        'label_test_email' => 'Test-E-Mail',
        'label_mailgun_domain' => 'Mailgun-Domain',
        'label_mailgun_secret' => 'Mailgun Secret',
        'label_postmark_token' => 'Postmarken-Token',
        'label_ses_key' => 'SES Key',
        'label_ses_secret' => 'SES secret',
        'label_ses_region' => 'SES Region',
        'label_permalink' => 'Permalinks',
        'label_enable_request_log' => 'Fehlerhafte Anfragen protokollieren',
        'label_maintenance_mode' => 'Wartungsarbeiten',
        'label_maintenance_message' => 'Wartungsmeldung',
        'label_activity_log_timeout' => 'Aktivitäten-Log löschen',

        'alert_email_sending' => 'E-Mail wird gesendet...',
        'alert_email_sent' => 'E-Mail gesendet an %s',
        'alert_settings_missing_model' => 'Definiertes Modell %s fehlt.',
        'alert_settings_not_found' => 'Einstellungen %s nicht gefunden.',
        'alert_settings_errors' => 'Klicken, um die fehlenden erforderlichen Einstellungselemente zu beheben.',
        'alert_delete_setup_files' => '<b>SICHERHEITS WARNUNG!</b> Löschen Sie die Setup-Dateien, um zu verhindern, dass jemand anders Ihre Website überschreibt.',

        'help_timezone' => 'Die Standard-Zeitzone. Wählen Sie eine Stadt in der gleichen Zeitzone wie Ihr Restaurant.',
        'help_detect_language' => 'Aktivieren oder deaktivieren Sie die Spracherkennung des Browsers. Wenn aktiviert, wird Ihre Seite in die Sprache des Browsers übersetzt.',
        'help_maps_api_key' => 'Für die Verwendung von Google Maps und/oder Geocoding wird ein API-Schlüssel benötigt. <a target="_blank" href="https://developers.google.com/maps/documentation/javascript/get-api-key#get-an-api-key">Wo finde ich meinen Google Maps API Key?</a> Google Maps Geocoding API und Google Maps JavaScript API in Ihrem Google Developer Account aktivieren',
        'help_default_geocoder' => 'Geben Sie dem System an, welcher Geokodierer-Dienst bei der Geokodierung verwendet werden soll. \'Chain\' ist ein spezieller Geocoder, der sowohl Google als auch Open Street Maps Geocoder läuft und stoppt, sobald er eine gültige Antwort erhält.',
        'help_site_currency' => 'Weitere Währungen aktivieren unter Lokalisierung > Währungen.',
        'help_currency_converter_oer_api' => 'Sie können sich <a target="_blank" href="https://openexchangerates.org/signup/">hier </a> für die Open Exchange Rates API anmelden.',
        'help_currency_converter_fixer_api' => 'Sie können <a target="_blank" href="https://fixer.io/signup/">sich hier</a> für Ihre Fixer.io API anmelden.',
        'help_special_category' => 'Wählen Sie die Kategorie, die automatisch für spezielle Menüs verwendet werden soll',
        'help_tax_mode' => 'Legen Sie fest, ob die Berechnung der Steuer im Front-End aktiviert oder deaktiviert werden soll',
        'help_tax_title' => 'Geben Sie den Steuertitel ein, wie er im Schaufenster angezeigt werden soll. Ex. MwSt.',
        'help_tax_percentage' => 'Geben Sie den Prozentsatz ein, um Steuern zu berechnen. Ex. 15',
        'help_tax_menu_price' => 'Legen Sie fest, ob der Menupreis bereits Steuern enthält oder ob die Steuern berechnet werden sollen',
        'help_tax_delivery_charge' => 'Legen Sie fest, ob die Liefergebühr steuerpflichtig ist',
        'help_default_location' => 'Wählen oder fügen Sie einen neuen Ort als Haupt- oder Standardstandort hinzu.',
        'help_default_order_status' => 'Standardauftragsstatus wählen, wenn eine neue Bestellung eingegangen/empfangen wird',
        'help_processing_order_status' => 'Wählen Sie den Bestellstatus aus, den eine Bestellung erreichen muss, bevor die Bestellung mit der Lagerbestandsreduzierung beginnt',
        'help_completed_order_status' => 'Wählen Sie den Bestellstatus aus, um eine Bestellung als abgeschlossen zu markieren, bevor die Auftragsrechnung erstellt wurde und ein Kunde eine Bewertung hinterlassen kann',
        'help_canceled_order_status' => 'Wählen Sie den Bestellstatus aus, wenn eine Bestellung storniert wird oder ein Verdacht auf betrügerische Aktivitäten besteht.',
        'help_menus_page' => 'Wählen Sie eine Seite zur Anzeige der Menüpunkte',
        'help_guest_order' => 'Kunden erlauben, eine Bestellung zu tätigen, ohne ein Konto zu erstellen.',
        'help_location_order' => 'Wenn diese Option deaktiviert ist, kann der Kunde bestellen, ohne seine Postleitzahl/Adresse einzugeben.',
        'help_invoice_prefix' => 'Setze das Rechnungspräfix (z.B. <b>INV-2015-00</b>1123). Leer lassen um kein Präfix zu verwenden. Die folgenden Makros sind verfügbar: {year} {month} {day} {hour} {minute} {second}',
        'help_default_reservation_status' => 'Wählen Sie den Standard Reservierungsstatus bei Erhalt einer neuen Reservierung',
        'help_canceled_reservation_status' => 'Wählen Sie den Reservierungsstatus aus, wenn eine Reservierung storniert wird oder ein Verdacht auf betrügerische Aktivitäten besteht.',
        'help_confirmed_reservation_status' => 'Wählen Sie den Reservierungsstatus aus, um eine Reservierung als bestätigt zu markieren, bevor ein Tisch reserviert ist',
        'help_delete_thumbs' => 'Dadurch werden alle erstellten Vorschaubilder gelöscht. Beachten Sie, dass Vorschaubilder automatisch erstellt werden.',
        'help_media_max_size' => 'Maximale Dateigröße (in Kilobytes) beim Hochladen.',
        'help_media_upload' => 'Datei-Upload aktivieren oder deaktivieren',
        'help_media_new_folder' => 'Ordnererstellung aktivieren oder deaktivieren',
        'help_media_copy' => 'Datei-/Ordner Kopieren aktivieren oder deaktivieren',
        'help_media_move' => 'Datei/Ordner verschieben aktivieren oder deaktivieren',
        'help_media_rename' => 'Datei/Ordner umbenennen aktivieren oder deaktivieren',
        'help_media_delete' => 'Löschen von Datei/Ordner aktivieren oder deaktivieren',
        'help_sendmail_path' => 'Bitte geben Sie den sendmail-Pfad an.',
        'help_allow_registration' => 'Wenn dies deaktiviert ist, können Kunden nur von Administratoren erstellt werden.',
        'help_registration_email' => 'Senden Sie eine Bestätigungsmail an den Kunden und/oder Admin-E-Mail nach erfolgreicher Registrierung',
        'help_order_email' => 'Senden Sie eine Bestätigungsmail an den Kunden, Admin und/oder Standort-E-Mail, nachdem eine neue Bestellung erstellt wurde',
        'help_reservation_email' => 'Senden Sie eine Bestätigungsmail an Kunden, Admin und/oder Standortmail, wenn eine neue Reservierung eingegangen ist',
        'help_enable_request_log' => 'Gibt an, ob fehlerhafte Browser-Anfragen protokolliert werden sollen, wie z. B. 404 Fehler.',
        'help_maintenance' => 'Aktivieren um Kunden daran zu hindern, Ihren Shop anzuzeigen. Die Wartungsmeldung wird Kunden mit Ausnahme des angemeldeten Administrators angezeigt.',
        'help_activity_log_timeout' => 'Lösche alle aufgezeichneten Aktivitäten, die älter als die angegebene Anzahl von Tagen sind',
    ],

    'system_logs' => [
        'text_title' => 'Systemprotokolle',

        'button_empty' => '<i class="fa fa-eraser"></i>&nbsp;&nbsp;Leere Protokolle',
        'button_request_logs' => '<i class="fa fa-globe"></i>&nbsp;&nbsp;Anfrage-Protokolle',
    ],

    'themes' => [
        'text_title' => 'Themes',
        'text_edit_title' => 'Thema: Anpassen',
        'text_source_title' => 'Theme: Template bearbeiten',
        'text_delete_title' => 'Theme: löschen',
        'text_form_name' => 'Theme',
        'text_tab_customize' => 'Anpassen',
        'text_tab_markup' => 'Markup',
        'text_tab_php_section' => 'PHP-Abschnitt',
        'text_tab_meta' => 'Metainformationen',
        'text_tab_components' => 'Komponenten',
        'text_empty' => 'Es stehen keine Themen zur Verfügung.',
        'text_select_file' => 'Wählen Sie eine [%s] Vorlage zum Bearbeiten',
        'text_is_default' => 'Aktiviert',
        'text_set_default' => 'Aktivieren',
        'text_author' => 'von',
        'text_version' => 'Version',
        'text_theme_is_active' => '. Sie können kein aktives Theme löschen.',
        'text_files' => 'Dateien',
        'text_files_data' => 'Dateien und Daten',
        'text_locked_child' => 'Gesperrtes Theme: Erstellen eines untergeordneten Themes',

        'label_code' => 'Code',
        'label_template' => 'Template',
        'label_file' => 'Template Dateiname',
        'label_title' => 'Titel',
        'label_layout' => 'Layout',
        'label_permalink' => 'Permalinks',
        'label_component' => 'Komponente',
        'label_component_alias' => 'Komponenten-Alias',
        'label_component_status' => 'Komponentenstatus',
        'label_delete_data' => 'Dateien löschen',
        'label_copy_data' => 'Daten kopieren',
        'label_type_page' => 'Seiten',
        'label_type_partial' => 'Partials',
        'label_type_layout' => 'Layouts',
        'label_type_content' => 'Inhalte',

        'button_browse' => '<i class="fa fa-globe"></i>&nbsp;&nbsp;Weitere Themes durchsuchen',
        'button_source' => '<i class="fa fa-file"></i>&nbsp;&nbsp;Vorlagendateien bearbeiten',
        'button_check' => '<i class="fa fa-refresh"></i>&nbsp;&nbsp;Updates',
        'button_customize' => '<i class="fa fa-paint-brush"></i>&nbsp;&nbsp;Anpassen',
        'button_child' => '<i class="fa fa-child"></i>&nbsp;&nbsp;Unter-Theme erstellen',
        'button_choose' => 'Wählen',
        'button_new_source' => 'Neue %s',
        'button_rename_source' => '%s umbenennen',
        'button_delete_source' => '%s löschen',
        'button_delete' => 'Löschen',
        'button_yes_delete' => 'Ja, löschen',
        'button_yes_copy' => 'Ja, kopieren',
        'button_return_to_list' => 'Nein, zurück zur Liste',

        'help_components' => 'Rendern Sie die Komponente auf einem Layout oder einer Seite, indem Sie <code>@component(&#x27;componentAlias&#x27;)</code> zum Markup hinzufügen. Mehr erfahren <a href="https://tastyigniter.com/docs/master/customize/components">here</a>.',

        'error_config_no_found' => 'Ein Fehler ist aufgetreten, die Theme-Registrierungsdatei konnte nicht gefunden werden',
        'error_theme_exists' => 'das Theme existiert bereits',

        'alert_delete_warning' => 'Sie sind dabei, %s des Themes <b>%s</b> zu löschen ',
        'alert_delete_confirm' => 'Sind Sie sicher, dass Sie die zugehörige %s löschen möchten? Dies kann nicht rückgängig gemacht werden!',
        'alert_theme_locked' => 'Dies ist ein gesperrtes Theme, Änderungen sind eingeschränkt, erstellen Sie ein Child-Theme, um Änderungen vorzunehmen.',
        'alert_theme_path_locked' => 'Diese Vorlage gehört zu einem gesperrten Theme, solche Aktionen sind eingeschränkt.',
        'alert_changes_confirm' => 'Konflikt zwischen Versionen - Template-Datei wurde geändert. Laden Sie die Seite neu, um fortzufahren.',
    ],

    'updates' => [
        'text_title' => 'Aktualisierungen',
        'text_browse_title' => '%s durchsuchen',

        'text_title_carte' => 'Dein Carté',

        'text_tab_title_extensions' => 'Erweiterungen',
        'text_tab_title_themes' => 'Themes',
        'text_ignore' => 'Ignorieren',
        'text_search' => 'Durchsuche den Marktplatz nach %s zur Installation',
        'text_popular_title' => 'Empfohlen %s',
        'text_last_checked' => '<b>Zuletzt überprüft:</b> %s',

        'text_no_updates' => 'Keine Aktualisierungen verfügbar.',

        'text_update_found' => '%s Aktualisierung(en) verfügbar',
        'text_update_ignored' => '%s Aktualisierung(en) ignoriert',
        'text_item_update_summary' => 'Update von Version %s auf <b>%s</b>',

        'text_maintenance_mode' => 'Während Ihre Seite aktualisiert wird, wird der Wartungsmodus aktiviert, sobald Ihre Updates abgeschlossen sind wird dieser wieder abgeschaltet.',

        'progress_download' => '<i class="fa fa-cloud-download fa-fw"></i>&nbsp;&nbsp;&nbsp;Herunterladen %s&#8230;',
        'progress_extract' => '<i class="fa fa-file-archive-o fa-fw"></i>&nbsp;&nbsp;&nbsp;Extrahieren %s&#8230;',
        'progress_complete' => '<i class="fa fa-download fa-fw"></i>&nbsp;&nbsp;&nbsp;Installation abgeschlossen&#8230;',

        'label_meta_code' => 'Meta Code',
        'label_meta_type' => 'Meta Type',
        'label_meta_version' => 'Meta-Version',
        'label_meta_hash' => 'Meta Hash',
        'label_meta_description' => 'Meta-Beschreibung',
        'label_meta_step' => 'Meta Step',
        'label_meta_action' => 'Meta Aktion',
        'label_meta_items' => 'Meta Elemente',

        'progress_success' => '<i class="fa fa-check fa-fw"></i>&nbsp;&nbsp;&nbsp;Erfolgreich %s %s beendet.&#8230;',
        'progress_update' => '<strong id="progress-updating">Aktualisiere %s&#8230;</strong>',
        'progress_enable_maintenance' => 'Aktiviere Wartungsmodus&#8230;',
        'progress_disable_maintenance' => 'Wartungsmodus wiederherstellen/deaktivieren &#8230;',

        'button_browse' => '<i class="fa fa-globe"></i>&nbsp;&nbsp;%s durchsuchen',
        'button_carte' => '<i class="fa fa-save"></i>&nbsp;&nbsp;Speichern',
        'button_check' => '<i class="fa fa-refresh"></i>&nbsp;&nbsp;erneut prüfen',
        'button_updates' => '<i class="fa fa-refresh"></i>&nbsp;&nbsp;Updates',
        'button_update' => '<i class="fa fa-check"></i>&nbsp;&nbsp;Update',

        'help_carte_key' => 'Ein Carte Key wird benötigt, um Artikel aus dem TastyIgniter Marktplatz hinzuzufügen/zu aktualisieren. Holen Sie sich einen, indem Sie eine Seite von Ihrem <a href="%s" target="_blank">TastyIgniter Konto</a> zu erstellen, falls Sie es noch nicht getan haben.',
    ],
];
