<?php

return [
    'side_menu' => 'Gutscheine',

    'permissions' => 'Gutscheine erstellen, bearbeiten und löschen',

    'text_title' => 'Gutscheine',
    'text_form_name' => 'Gutschein',
    'text_tab_general' => 'Allgemein',
    'text_tab_restrictions' => 'Einschränkungen',
    'text_tab_history' => 'Verlauf',
    'text_filter_search' => 'Suche nach Namen, Code oder Gültigkeit.',
    'text_filter_type' => 'Alle Typen anzeigen',
    'text_empty' => 'Es sind keine Gutscheine verfügbar.',
    'text_fixed_amount' => 'Festbetrag',
    'text_percentage' => 'Prozentsatz',
    'text_forever' => 'Für immer',
    'text_fixed' => 'Festgelegt',
    'text_period' => 'Zeitraum',
    'text_recurring' => 'Wiederkehrend',
    'text_delivery_only' => 'Nur Lieferung',
    'text_collection_only' => 'Nur Abholung',
    'text_redeemed' => 'Eingelöst',
    'text_not_redeemed' => 'Noch nicht eingelöst',
    'text_coupon' => 'Gutschein [%s]',

    'alert_coupon_login_required' => 'Please login or register to use this coupon',

    'column_code' => 'Code',
    'column_discount' => 'Rabatt',
    'column_validity' => 'Gültigkeit',
    'column_order_id' => 'Bestell-Nr.',
    'column_customer' => 'Kunde',
    'column_amount' => 'Gesamtbetrag',
    'column_min_total' => 'Mindestbestellwert',
    'column_date_used' => 'Verwendetes Datum',
    'column_count' => 'Erlösungsanzahl',

    'label_code' => 'Code',
    'label_discount' => 'Rabatt',
    'label_min_total' => 'Mindestsumme',
    'label_redemption' => 'Einlösung',
    'label_customer_redemption' => 'Kundeneinlösung',
    'label_validity' => 'Gültigkeit',
    'label_order_restriction' => 'Bestellbeschränkung',
    'label_cart_restriction' => 'Nicht auf den gesamten Warenkorb anwenden',
    'label_categories' => 'Auf Menüpunkte aus diesen Kategorien anwenden',
    'label_menus' => 'Auf diese Menüeinträge anwenden',
    'label_date' => 'Datum',
    'label_fixed_date' => 'Fester Termin',
    'label_fixed_from_time' => 'Fixiert von Zeit',
    'label_fixed_to_time' => 'Fixiert auf Zeit',
    'label_period_start_date' => 'Beginndatum',
    'label_period_end_date' => 'Enddatum',
    'label_recurring_every' => 'Wiederkehrende jeden',
    'label_recurring_from_time' => 'Wiederkehrende von Zeit',
    'label_recurring_to_time' => 'Wiederkehrende, Zeit',
    'label_auto_apply' => 'Automatisch anwenden',

    'help_type' => 'Ob ein fester Betrag oder Prozentsatz von Bestellsumme abgezogen.',
    'help_redemption' => 'Die Gesamtzahl der Male, die dieser Gutschein eingelöst werden kann. Auf 0 setzen, um eine beliebige Anzahl von Einlösen zu ermöglichen.',
    'help_customer_redemption' => 'Die Anzahl der Male, die ein bestimmter Kunde diesen Gutschein einlösen kann. Auf 0 setzen, um eine beliebige Anzahl von Einlösen zu ermöglichen.',
    'help_order_restriction' => 'Gibt an, ob der Gutschein auf einen bestimmten Auftragstyp beschränkt werden soll.',
    'help_locations' => 'Wenden Sie diesen Gutschein NUR bei Bestellungen an den ausgewählten Standort(en) an. Lassen Sie leer, um den Gutschein an allen Standorten verfügbar zu machen',
    'help_categories' => 'Benutzen Sie diesen Gutschein NUR auf Menüeinträge in der Reihenfolge, die in diesen/diesen Kategorien erscheint. Lassen Sie leer, um den Gutschein für alle Artikel verfügbar zu machen',
    'help_menus' => 'Wenden Sie diesen Gutschein NUR bei Bestellungen an den ausgewählten Standort(en) an. Lassen Sie leer, um den Gutschein an allen Standorten verfügbar zu machen',
    'help_coupon_condition' => 'Gutschein auf den Warenkorb anwenden.',
];
