<?php

return [
    'text_tab_general' => 'Allgemein',
    'text_tab_common_tags' => 'Gewöhnliche Tags',
    'text_tab_seo' => 'SEO',
    'text_tab_og' => 'Graph öffnen',
    'text_prefix' => 'Am Anfang',
    'text_suffix' => 'Am Ende',
    'text_permission' => 'Fähigkeit, den Seo-Manager zu verwalten.',

    'component_name' => 'SEO-Tags',
    'component_desc' => 'SEO-Tags einfügen',
    'setting_title' => 'SEO-Konfiguration',
    'setting_desc' => 'SEO Meta und Open Graph Tags konfigurieren.',

    'label_meta_title' => 'Meta-Titel',
    'label_meta_description' => 'Meta-Beschreibung',
    'label_meta_keywords' => 'Meta Keywords',
    'label_canonical_url' => 'Canonical URL',
    'label_redirect_url' => 'Weiterleitungs-URL',
    'label_robot_index' => 'Robot-Index',
    'label_robot_follow' => 'Robot Follow',
    'label_robot_advanced' => 'Roboter Erweitert',
    'label_og_title' => 'Titel',
    'label_og_type' => 'Typ',
    'label_og_description' => 'Beschreibung',
    'label_og_image' => 'Bild',

    'label_enable_title' => 'Aktivieren, wenn der Seitenname im Titeltag verwendet werden soll',
    'label_title' => 'Seitenname',
    'label_title_position' => 'Wo der Seitenname erscheinen soll',
    'label_favicon' => 'Favicon',
    'label_app_icon' => 'App Icon',
    'label_common_tags' => 'Geben Sie Tags an, die für alle Seiten gemeinsam sind',
    'label_enable_og_tags' => 'Open Graph(og) Tags aktivieren',
    'label_og_site_name' => 'Der Name Ihrer Website. Nicht die URL, sondern der Name.',
    'label_og_fb_appid' => 'Facebook App-ID',
    'label_og_tags' => 'Was ist Open Graph?',

    'help_favicon' => '16x16, 32x32 oder 64x64 Pixel png verwenden',
    'help_app_icon' => 'Homescreen-Symbol für mobile Geräte',
    'help_meta_title' => 'Die Titelanzeige in Suchmaschinen ist auf 60 Zeichen beschränkt, lassen Sie leer auf die Standardeinstellung des Seitentitels.',
    'help_meta_description' => 'Empfohlene Beschreibung sollte zwischen 50–300 Zeichen lang sein, lassen Sie leer auf die Standardbeschreibung der Seite. ',
    'help_canonical_url' => 'Die kanonische URL, auf die diese Seite verweisen soll, lassen Sie leer auf die Voreinstellung permalink.',
    'help_redirect_url' => 'Die URL, auf die diese Seite weitergeleitet werden soll.',
    'help_robot_advanced' => 'Fügen Sie weitere Robot Meta Werte wie noarchive, noodp, noydir, etc. hinzu.',
    'help_og_title' => 'Leer lassen zum Standardwert beim SEO Meta Titel',
    'help_og_tags' => 'Das Open Graph Protokoll ermöglicht es jeder Webseite, ein reiches Objekt in einem sozialen Diagramm zu werden.<br> Derzeit enthaltene Open Graph Tags sind: fb:app_id, og:site_name, og:title, og:url, og:description, og:type und og:image',
    'help_og_type' => 'Der Typ des Objekts, wie "Artikel". <a href="https://developers.facebook.com/docs/sharing/webmasters/">Siehe Facebook Docs</a>',
    'help_og_description' => 'Leer lassen auf Standard der SEO Meta Beschreibung',
    'help_og_image' => 'Verwenden Sie Bilder, die mindestens 1200 x 630 Pixel für das beste Display auf hochauflösenden Geräten sind',
];